# Import & Constants

In [1]:
import pandas as pd
import numpy as np

In [2]:
JOINT_NAMES = ['RootJoint', 'lHip', 'lKnee', 'lAnkle', 'lToeJoint', 'rHip', 'rKnee', 'rAnkle', 'rToeJoint',
               'pelvis_lowerback', 'lowerback_torso', 'torso_head', 'lTorso_Clavicle', 'lShoulder', 'lElbow',
               'lWrist', 'rTorso_Clavicle', 'rShoulder', 'rElbow', 'rWrist']
JOINT_MPE_NAMES = ['{}_MPE'.format(j) for j in JOINT_NAMES]
JOINT_MRE_NAMES = ['{}_MRE'.format(j) for j in JOINT_NAMES]
JOINT_MCPE_NAMES = ['{}_MPE_change'.format(j) for j in JOINT_NAMES]
JOINT_MCRE_NAMES = ['{}_MRE_change'.format(j) for j in JOINT_NAMES]

In [3]:
BML_movi = pd.read_csv('BMLmovi.csv')
BML_rub = pd.read_csv('BMLrub.csv')
CMU = pd.read_csv('CMU.csv')
DanceDB = pd.read_csv('DanceDB.csv')
EKUT = pd.read_csv('EKUT.csv')
Eyes = pd.read_csv('Eyes.csv')
MPI_HDM05 = pd.read_csv('MPI_HDM05.csv')
MPI_Limits = pd.read_csv('MPI_Limits.csv')
MPI_mosh = pd.read_csv('MPI_mosh.csv')
SFU = pd.read_csv('SFU.csv')
Transitions = pd.read_csv('Transitions.csv')
Accad = pd.read_csv('accad.csv')
ALL_DFS = {'BML_movi': BML_movi,
           'BML_rub': BML_rub,
           'CMU': CMU,
           'DanceDB': DanceDB,
           'EKUT': EKUT,
           'Eyes': Eyes,
           'MPI_HDM05': MPI_HDM05,
           'MPI_Limits': MPI_Limits,
           'MPI_mosh': MPI_mosh,
           'SFU': SFU,
           'Transitions': Transitions,
           'Accad': Accad
           }

# Analyze Individual Datasets

## ACCAD (Part of Training Set)

In [4]:
Accad['MPJPE'] = Accad[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
Accad['MPJRE'] = Accad[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [5]:
Accad.loc[:, ~Accad.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max    17.074574         53.006213        6361.000000     8.333000e-03   
mean    4.408413          6.367239         764.099206     8.333000e-03   
min     2.438459          1.691599         203.000000     8.333000e-03   
std     1.859329          6.150569         738.097745     3.302534e-17   
50%     3.983152          4.533152         544.000000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max        52.997880      6360.000000        1262.000000  0.338605  1.306874  
mean        6.311652       757.428571          58.757937  0.073408  0.490834  
min         1.599936       192.000000           0.000000  0.017600  0.010789  
std         6.145243       737.458621         105.335439  0.045736  0.261178  
50%         4.399824       528.000000          40.000000  0.061361  0.460838

In [6]:
display(Accad.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  clip_time_origin  \
110  Male2General_c3d_A5- Pick up box_poses.bvh    4.693675          5.983094   
251                      s011_walkdog_poses.bvh    6.597713         16.291015   
109  Male2General_c3d_A4- Look Around_poses.bvh    6.676110         16.049358   

     num_frames_origin  frame_time_imit  clip_time_imit  num_frames_imit  \
110                718         0.008333        5.999760              720   
251               1955         0.008333       16.199352             1944   
109               1926         0.008333       15.999360             1920   

     success  frame_imit_starts  RootJoint_MPE  ...  lTorso_Clavicle_MRE  \
110    False                442       0.094266  ...             0.241013   
251    False                826       0.425389  ...             0.229168   
109    False               1262       0.012982  ...             0.093639   

     lShoulder_MRE  lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  \
110       0.480963    0.555604    0.263205             0.189962   
251       0.406181    1.078095    0.324391             0.118753   
109       0.056104    0.061554    0.052032             0.114551   

     rShoulder_MRE  rElbow_MRE  rWrist_MRE     MPJPE     MPJRE  
110       0.468277    0.786490    0.195322  0.030484  0.263873  
251       0.326195    0.373902    0.257508  0.069786  0.451370  
109       0.146875    0.055618    0.073404  0.023600  0.423993  

[3 rows x 51 columns]

In [7]:
display(Accad[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(Accad[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(Accad[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max        4.347349  1.684091e-07   0.217118    0.267065       0.281059   
mean       0.510837  6.154284e-08   0.061732    0.088647       0.100690   
min        0.004402  1.904570e-08   0.007199    0.013410       0.022155   
std        0.597964  3.893035e-08   0.034100    0.047523       0.050179   
50%        0.257984  4.124888e-08   0.051613    0.076726       0.087300   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   1.641876e-07   0.197556    0.239343       0.248399   
mean  6.158920e-08   0.061214    0.086985       0.099819   
min   1.749995e-08   0.011612    0.009423       0.010971   
std   3.854566e-08   0.032378    0.045225       0.047980   
50%   4.025061e-08   0.051260    0.076569       0.090980   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           1.643924e-07             0.053872        0.211589   
mean          6.565872e-08             0.014181        0.036617   
min           2.010388e-08             0.001121        0.004354   
std           3.823582e-08             0.006967        0.020590   
50%           4.626436e-08             0.012878        0.032924   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.138331       0.118351    0.170859    0.256737   
mean             0.025509       0.030450    0.069916    0.081483   
min              0.002377       0.011085    0.014218    0.030109   
std              0.013735       0.015068    0.028181    0.039313   
50%              0.023391       0.027548    0.063440    0.072706   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.138966       0.172504    0.209004    0.283853  
mean             0.025486       0.029806    0.065785    0.079002  
min              0.002365       0.008721    0.008144    0.013007  
std              0.013759       0.016387    0.025555    0.039068  
50%              0.023353       0.026946    0.062286    0.070394

max     RootJoint_MPE
mean    RootJoint_MPE
min        lWrist_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max                 rHip_MPE
mean                lHip_MPE
min                 rHip_MPE
std     pelvis_lowerback_MPE
50%                 rHip_MPE
dtype: object

In [8]:
display(Accad[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(Accad[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(Accad[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        8.718720  2.077816   1.982749    1.311946       0.588373  1.964765   
mean       2.191303  0.281853   0.350771    0.247390       0.133569  0.270265   
min        0.004108  0.008652   0.010619    0.005740       0.000800  0.004387   
std        1.848183  0.388302   0.365786    0.198067       0.104288  0.364292   
50%        1.881011  0.173822   0.255071    0.195667       0.112719  0.176876   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    1.918924    1.186512       0.690255              1.677794   
mean   0.338116    0.265227       0.139877              0.167965   
min    0.009492    0.008021       0.000341              0.006702   
std    0.333967    0.194680       0.107328              0.148691   
50%    0.243603    0.223560       0.123058              0.132645   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              1.056456        0.970967             0.882225       0.681342   
mean             0.178121        0.223499             0.180631       0.277687   
min              0.013906        0.010576             0.009628       0.016171   
std              0.187857        0.159739             0.157354       0.123845   
50%              0.131474        0.178994             0.126511       0.264129   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     6.891146    1.409166             0.967580       0.765617    6.533239   
mean    2.019190    0.287629             0.168589       0.258151    1.543271   
min     0.015529    0.027032             0.007168       0.015406    0.020846   
std     1.997586    0.199268             0.157179       0.128487    1.640410   
50%     1.041722    0.241067             0.119217       0.236030    0.852760   

      rWrist_MRE  
max     1.683683  
mean    0.293568  
min     0.018967  
std     0.218400  
50%     0.247934

max     RootJoint_MRE
mean    RootJoint_MRE
min        lWrist_MRE
std        lElbow_MRE
50%     RootJoint_MRE
dtype: object

max     lToeJoint_MRE
mean    lToeJoint_MRE
min     rToeJoint_MRE
std     lToeJoint_MRE
50%     lToeJoint_MRE
dtype: object

In [9]:
display(Accad.sort_values(by=['MPJPE']).head(3)['file_name'])
display(Accad.sort_values(by=['MPJPE']).tail(3)['file_name'])

115         Male2General_c3d_male2 Calibration_poses.bvh
142    Male2MartialArtsKicks_c3d_male2 Subject Cal 2_...
10                Female1General_c3d_A4 - look_poses.bvh
Name: file_name, dtype: object

77    Male1General_c3d_General A12 -   Military Craw...
21          Female1Gestures_c3d_D6- CartWheel_poses.bvh
20    Female1Gestures_c3d_D5 - Random Stuff 2_poses.bvh
Name: file_name, dtype: object

In [10]:
display(Accad.sort_values(by=['MPJRE']).head(3)['file_name'])
display(Accad.sort_values(by=['MPJRE']).tail(3)['file_name'])

234    MartialArtsWalksTurns_c3d_E19 - dodge left t2_...
0                Female1General_c3d_A1 - Stand_poses.bvh
103                 Male2General_c3d_A1- Stand_poses.bvh
Name: file_name, dtype: object

2       Female1General_c3d_A11 - crawl forward_poses.bvh
105                Male2General_c3d_A11- Crawl_poses.bvh
76     Male1General_c3d_General A11 -   Military Craw...
Name: file_name, dtype: object

In [11]:
print("Success: {} out of {}".format(np.sum(Accad['success'] == True), len(Accad)))
print("Success %: {}".format(np.sum(Accad['success'] == True)/len(Accad) * 100))

Success: 6 out of 252
Success %: 2.380952380952381


### Investigation Summary

Nothing too irregular with motions that start matching later.
Although it does seem that head/neck motion is weird (fails to track well).

Minimum mean position error when there is not much motion or motion mainly with only arms. The minimum mean error Female1General_c3d_A4 - look_poses.bvh actually performs badly. Has low error but since it deals with movement of single joint. The imitated motion does not move much as all. Could it be due to lack of importance recognition during imitation or just not enough head/single joint movement examples? <br>

Maximum mean position error when extremely mobile cases
- martial arts round kick fails to balance when doing high kicks and stumbles a bit.
- Fails cartwheel and lands face first. Does get up in a natural way though. Visualizing in simulation seems to be not using hand to help. Would need further investigation to understand though.
<br>

Minimum mean rotation error: again when there are not much motion changes or single joint (non head). <br>
Maximum mean rotation error: worst when crawling. hand interaction with ground has different rotation. hand penetration with gbround is fixed but weird angles (constraints to the bodies not respecterd). Crawling recordings also has most problem with ground penetration. ALso failes to move forward, based on kinematics seems like it is failing to utilize the hand to pull forward especially in millitary crawling.<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip joints <br>

Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: Toe joints <br>

For rotations, elbow and wrist seem to be an issue.
For positions, ankle and toes also seem to be an issue.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (only 6 / 252).

## BMLmovi (Part of Training Set)

In [12]:
BML_movi['MPJPE'] = BML_movi[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
BML_movi['MPJRE'] = BML_movi[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [13]:
BML_movi.loc[:, ~BML_movi.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max    10.347959         21.107489        2533.000000     8.333000e-03   
mean    3.413493          5.629633         675.583009     8.333000e-03   
min     2.013797          1.141621         137.000000     8.333000e-03   
std     0.983170          2.850088         342.024249     2.550752e-16   
50%     3.076161          4.574817         549.000000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max        20.999160      2520.000000         641.000000  0.286444  0.986129  
mean        5.572681       668.748473          33.363132  0.041822  0.384683  
min         0.999960       120.000000           0.000000  0.013270  0.022986  
std         2.851400       342.181679          43.366824  0.024310  0.141296  
50%         4.599816       552.000000          24.000000  0.035588  0.370113

In [14]:
display(BML_movi.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  \
548   Subject_36_F_MoSh_Subject_36_F_15_poses.bvh    2.855400   
1264  Subject_68_F_MoSh_Subject_68_F_18_poses.bvh    3.352146   
145   Subject_18_F_MoSh_Subject_18_F_11_poses.bvh    3.907694   

      clip_time_origin  num_frames_origin  frame_time_imit  clip_time_imit  \
548           4.308161                517         0.008333        4.199832   
1264          6.541405                785         0.008333        6.399744   
145           8.241337                989         0.008333        8.199672   

      num_frames_imit  success  frame_imit_starts  RootJoint_MPE  ...  \
548               504     True                466       0.013563  ...   
1264              768    False                517       0.110480  ...   
145               984    False                641       0.103201  ...   

      lTorso_Clavicle_MRE  lShoulder_MRE  lElbow_MRE  lWrist_MRE  \
548              0.030453       0.093622    0.111490    0.313127   
1264             0.064062       0.184446    1.739844    0.240272   
145              0.061866       0.152147    0.074231    0.065050   

      rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  rWrist_MRE     MPJPE  \
548              0.030449       0.083674    0.111394    0.249624  0.022027   
1264             0.077468       0.165438    1.746170    0.155204  0.032806   
145              0.046918       0.105411    0.096347    0.078874  0.036967   

         MPJRE  
548   0.064427  
1264  0.500888  
145   0.123083  

[3 rows x 51 columns]

In [15]:
display(BML_movi[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(BML_movi[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(BML_movi[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max        1.378438  5.508356e-08   0.298648    0.441428       0.512381   
mean       0.147505  3.017550e-08   0.040058    0.067738       0.073100   
min        0.004508  1.924511e-08   0.005589    0.006868       0.011484   
std        0.191747  4.831607e-09   0.026915    0.042509       0.044311   
50%        0.069288  2.820642e-08   0.034755    0.058887       0.063860   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   5.638577e-08   0.269328    0.349164       0.366358   
mean  3.015394e-08   0.036539    0.058737       0.064381   
min   2.025889e-08   0.003688    0.006522       0.010161   
std   4.884415e-09   0.021088    0.035694       0.037636   
50%   2.821693e-08   0.033448    0.053758       0.058809   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           6.357634e-08             0.056922        0.171854   
mean          3.690529e-08             0.011854        0.024400   
min           1.848165e-08             0.001585        0.003929   
std           5.169272e-09             0.007185        0.015923   
50%           3.605356e-08             0.010322        0.021354   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.115978       0.144516    0.276809    0.459268   
mean             0.017460       0.021148    0.049329    0.069291   
min              0.003137       0.005435    0.010248    0.014436   
std              0.011175       0.012010    0.023284    0.039477   
50%              0.015389       0.018604    0.044462    0.059060   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.116404       0.150712    0.390020    0.635031  
mean             0.017452       0.021640    0.047697    0.068104  
min              0.003111       0.004777    0.012623    0.013832  
std              0.011173       0.012225    0.023209    0.039900  
50%              0.015376       0.019047    0.042822    0.057735

max     RootJoint_MPE
mean    RootJoint_MPE
min        lWrist_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max                 lHip_MPE
mean                rHip_MPE
min     pelvis_lowerback_MPE
std                 lHip_MPE
50%                 lHip_MPE
dtype: object

In [16]:
display(BML_movi[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(BML_movi[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(BML_movi[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        8.246992  0.854144   1.258491    1.148918       0.619039  0.801789   
mean       2.029320  0.137398   0.198276    0.189049       0.179522  0.128133   
min        0.015920  0.006137   0.007383    0.007066       0.008296  0.007828   
std        1.526516  0.089942   0.139379    0.144607       0.091696  0.078641   
50%        1.682360  0.119271   0.183382    0.153967       0.161142  0.117972   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    0.936754    1.285588       0.741320              0.742475   
mean   0.188120    0.189502       0.201007              0.103438   
min    0.011399    0.010549       0.012777              0.010070   
std    0.126836    0.135428       0.100525              0.074573   
50%    0.177500    0.161001       0.186933              0.085273   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              0.614515        0.661391             0.601861       0.939776   
mean             0.100300        0.176317             0.146462       0.272128   
min              0.006501        0.012012             0.011195       0.025224   
std              0.067750        0.082340             0.066564       0.113364   
50%              0.081041        0.160071             0.135072       0.253686   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     6.235543    1.554194             0.712708       0.846637    7.220900   
mean    1.043904    0.285594             0.139344       0.279515    1.400658   
min     0.036729    0.017604             0.005572       0.026911    0.022111   
std     1.180048    0.181375             0.061096       0.121628    1.421380   
50%     0.443385    0.240909             0.129907       0.257573    0.700639   

      rWrist_MRE  
max     1.573347  
mean    0.305674  
min     0.018888  
std     0.195345  
50%     0.262738

max     RootJoint_MRE
mean    RootJoint_MRE
min        lElbow_MRE
std     RootJoint_MRE
50%     RootJoint_MRE
dtype: object

max     lTorso_Clavicle_MRE
mean    lowerback_torso_MRE
min     rTorso_Clavicle_MRE
std     rTorso_Clavicle_MRE
50%     lowerback_torso_MRE
dtype: object

In [17]:
display(BML_movi.sort_values(by=['MPJPE']).head(3)['file_name'])
display(BML_movi.sort_values(by=['MPJPE']).tail(3)['file_name'])

1008    Subject_57_F_MoSh_Subject_57_F_13_poses.bvh
1006    Subject_57_F_MoSh_Subject_57_F_11_poses.bvh
496      Subject_33_F_MoSh_Subject_33_F_5_poses.bvh
Name: file_name, dtype: object

441     Subject_31_F_MoSh_Subject_31_F_13_poses.bvh
349      Subject_27_F_MoSh_Subject_27_F_5_poses.bvh
1497     Subject_78_F_MoSh_Subject_78_F_1_poses.bvh
Name: file_name, dtype: object

In [18]:
display(BML_movi.sort_values(by=['MPJRE']).head(3)['file_name'])
display(BML_movi.sort_values(by=['MPJRE']).tail(3)['file_name'])

395      Subject_29_F_MoSh_Subject_29_F_9_poses.bvh
1067      Subject_5_F_MoSh_Subject_5_F_10_poses.bvh
135     Subject_17_F_MoSh_Subject_17_F_21_poses.bvh
Name: file_name, dtype: object

867     Subject_50_F_MoSh_Subject_50_F_19_poses.bvh
601      Subject_38_F_MoSh_Subject_38_F_4_poses.bvh
1315       Subject_6_F_MoSh_Subject_6_F_6_poses.bvh
Name: file_name, dtype: object

In [19]:
print("Success: {} out of {}".format(np.sum(BML_movi['success'] == True), len(BML_movi)))
print("Success %: {}".format(np.sum(BML_movi['success'] == True)/len(BML_movi) * 100))


Success: 20 out of 1801
Success %: 1.1104941699056081


### Investigation Summary

Nothing too irregular with motions that start matching later.

Still has problem with head/neck movements, specifically isolated scenarios.

Maximum mean position error when trying to sit down. Fails to cross leg, could this be simulation vs reality? Would be worth understanding through training for it as a skill. Or could it be caused by the network which prevents fall ? Thinks sitting down is falling? Also fails at balancing with one hand and one leg when trying to climb on the ground, diffferent from crawl only knees and hands on the ground. Fails to get back up naturally when on the back.
<br>
Maximum mean rotation error: elbow rotation is high as well
An issue with numerics don't include problem with mocap data -> overlapping 'Subject_38_F_MoSh_Subject_38_F_4_poses.bvh' has overlapping hands in mocap but physically impossible. Fixed in simulation
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: torso and back <br>

similar issue with elbow, wrist, toe and ankles.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (only 20 / 1801).

## BMLrub (Part of Training Set)

In [20]:
BML_rub['MPJPE'] = BML_rub[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
BML_rub['MPJRE'] = BML_rub[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [21]:
BML_rub.loc[:, ~BML_rub.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max    42.128680        132.986347       15959.000000     8.333000e-03   
mean    5.370149         10.251606        1230.241909     8.333000e-03   
min     2.155075          0.466648          56.000000     8.333000e-03   
std     4.659808         15.136169        1816.412975     3.018912e-16   
50%     3.953210          5.308121         637.000000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max       132.994680     15960.000000        2792.000000  1.042555  1.058874  
mean       10.196454      1223.623406          56.146453  0.126307  0.362925  
min         0.399984        48.000000           0.000000  0.015803  0.005013  
std        15.136644      1816.469909         101.232122  0.147963  0.181294  
50%         5.199792       624.000000          40.000000  0.076985  0.346620

In [22]:
display(BML_rub.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  \
2955                rub109_0030_scamper_poses.bvh    7.934449   
300   rub012_0021_catching_and_throwing_poses.bvh   10.361426   
1570  rub060_0021_catching_and_throwing_poses.bvh    9.470014   

      clip_time_origin  num_frames_origin  frame_time_imit  clip_time_imit  \
2955         20.574177               2469         0.008333       20.599176   
300          23.415730               2810         0.008333       23.399064   
1570         23.357399               2803         0.008333       23.399064   

      num_frames_imit  success  frame_imit_starts  RootJoint_MPE  ...  \
2955             2472    False               1086       1.502233  ...   
300              2808    False               2331       0.026989  ...   
1570             2808    False               2792       0.001979  ...   

      lTorso_Clavicle_MRE  lShoulder_MRE  lElbow_MRE  lWrist_MRE  \
2955             0.113000       0.163014    2.389035    0.193470   
300              0.142878       0.097169    7.128473    0.692551   
1570             0.020697       0.022578    0.026821    0.013247   

      rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  rWrist_MRE     MPJPE  \
2955             0.149116       0.193219    1.280563    0.286600  0.127039   
300              0.074068       0.091822    2.476517    0.305332  0.026286   
1570             0.006677       0.014958    0.018661    0.017363  0.034788   

         MPJRE  
2955  0.515756  
300   0.644098  
1570  0.100849  

[3 rows x 51 columns]

In [23]:
display(BML_rub[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(BML_rub[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(BML_rub[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max       19.592587  4.433188e-07   0.152666    0.256209       0.267169   
mean       1.641779  6.537284e-08   0.053856    0.084678       0.095394   
min        0.000574  1.656116e-08   0.005351    0.010581       0.016530   
std        2.934547  5.982988e-08   0.020459    0.038297       0.039690   
50%        0.532688  4.561712e-08   0.049889    0.073321       0.084211   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   4.352996e-07   0.152736    0.225869       0.267280   
mean  6.550586e-08   0.051173    0.083414       0.091852   
min   1.945887e-08   0.008601    0.009902       0.009651   
std   5.946638e-08   0.017243    0.033213       0.038298   
50%   4.603831e-08   0.048269    0.075656       0.081832   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           4.449277e-07             0.048234        0.096761   
mean          7.163699e-08             0.013211        0.030382   
min           1.937788e-08             0.001197        0.002173   
std           5.831374e-08             0.005293        0.010119   
50%           5.216496e-08             0.012634        0.029416   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.067381       0.083408    0.135822    0.211204   
mean             0.021688       0.026095    0.061476    0.083453   
min              0.003022       0.004496    0.009321    0.009479   
std              0.007394       0.007942    0.018464    0.024902   
50%              0.021085       0.025248    0.060243    0.081196   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.067395       0.078651    0.162427    0.237445  
mean             0.021657       0.026836    0.060952    0.078236  
min              0.002971       0.004834    0.010484    0.012665  
std              0.007385       0.007859    0.019215    0.025495  
50%              0.021057       0.026084    0.059207    0.074935

max     RootJoint_MPE
mean    RootJoint_MPE
min     lToeJoint_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max                 rHip_MPE
mean                lHip_MPE
min                 lHip_MPE
std     pelvis_lowerback_MPE
50%                 lHip_MPE
dtype: object

In [24]:
display(BML_rub[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(BML_rub[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(BML_rub[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        7.983143  0.635350   0.901309    0.880337       0.674751  0.488124   
mean       2.071962  0.184649   0.302736    0.232312       0.145782  0.173716   
min        0.001087  0.003120   0.003047    0.004050       0.000654  0.001921   
std        2.254388  0.078952   0.123353    0.114251       0.109095  0.064073   
50%        0.754764  0.173470   0.292945    0.210158       0.122726  0.167128   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    0.739699    0.851376       0.746565              0.402533   
mean   0.264463    0.216476       0.128702              0.139978   
min    0.003595    0.002849       0.000151              0.003628   
std    0.103786    0.105217       0.098730              0.052739   
50%    0.256375    0.199131       0.110719              0.134730   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              0.380959        0.998107             0.493373       1.356465   
mean             0.114197        0.160757             0.131174       0.232713   
min              0.004244        0.002667             0.001793       0.006201   
std              0.044915        0.091286             0.059121       0.106334   
50%              0.106613        0.144809             0.117459       0.209594   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max    10.101935    2.636755             0.436258       0.772188    9.133684   
mean    0.996732    0.260705             0.124788       0.223183    0.880165   
min     0.012960    0.010022             0.003898       0.006546    0.004792   
std     1.428451    0.150338             0.052556       0.100180    1.156931   
50%     0.387016    0.226001             0.116009       0.202671    0.402250   

      rWrist_MRE  
max     1.729617  
mean    0.273302  
min     0.006563  
std     0.175166  
50%     0.233723

max        lElbow_MRE
mean    RootJoint_MRE
min        lElbow_MRE
std     RootJoint_MRE
50%     RootJoint_MRE
dtype: object

max     lowerback_torso_MRE
mean    lowerback_torso_MRE
min           rToeJoint_MRE
std     lowerback_torso_MRE
50%     lowerback_torso_MRE
dtype: object

In [25]:
display(BML_rub.sort_values(by=['MPJPE']).head(3)['file_name'])
display(BML_rub.sort_values(by=['MPJPE']).tail(3)['file_name'])

1306        rub051_0004_motorcycle_poses.bvh
946         rub038_0004_motorcycle_poses.bvh
2164    rub080_0023_throwing_hard2_poses.bvh
Name: file_name, dtype: object

2960    rub110_0003_treadmill_jog_poses.bvh
2587    rub096_0003_treadmill_jog_poses.bvh
2906    rub108_0003_treadmill_jog_poses.bvh
Name: file_name, dtype: object

In [26]:
display(BML_rub.sort_values(by=['MPJRE']).head(3)['file_name'])
display(BML_rub.sort_values(by=['MPJRE']).tail(3)['file_name'])

1761    rub067_0004_motorcycle_poses.bvh
26      rub002_0004_motorcycle_poses.bvh
855     rub035_0004_motorcycle_poses.bvh
Name: file_name, dtype: object

967                  rub038_0026_kicking2_poses.bvh
2046    rub076_0021_catching_and_throwing_poses.bvh
1830              rub069_0012_normal_jog4_poses.bvh
Name: file_name, dtype: object

In [27]:
print("Success: {} out of {}".format(np.sum(BML_rub['success'] == True), len(BML_rub)))
print("Success %: {}".format(np.sum(BML_rub['success'] == True)/len(BML_rub) * 100))


Success: 36 out of 3059
Success %: 1.1768551814318404


### Investigation Summary

It is clear that the root movement or in general movement of the simulated
don't move as much as the real movement. Wrist movements are also lacking.
Suddeen movements are also not matching (dynamics).

Maximum mean position error: (object interactions) Interesting enough 'rub110_0003_treadmill_jog_poses.bvh' in simulation doesn't change position due to treadmill in real life. However the simulation has friction so the humanoid moves
<br>


Maximum mean rotation error: no major issues not mentioned before
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: torso and back <br>

similar issue with elbow, wrist, toe and ankles.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (only 36 / 3059).

## CMU (Part of Training Set)

In [28]:
CMU['MPJPE'] = CMU[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
CMU['MPJRE'] = CMU[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [29]:
CMU.loc[:, ~CMU.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max    52.794998        191.225684       22948.000000     8.333000e-03   
mean    6.346724         15.946444        1691.301205     8.333000e-03   
min     1.960391          0.808301          74.000000     8.333000e-03   
std     4.974781         18.078905        2145.089516     2.706821e-16   
50%     4.677462          9.683527         884.000000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max       191.192352     22944.000000        5646.000000  0.598558  1.428773  
mean       15.890063      1906.883855          76.396145  0.089779  0.414358  
min         0.799968        96.000000           4.000000  0.018247  0.003216  
std        18.077831      2169.426442         255.969398  0.063011  0.199923  
50%         9.599616      1152.000000          40.000000  0.067764  0.395364

In [30]:
display(CMU.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  clip_time_origin  num_frames_origin  \
1403  55_55_28_poses.bvh   20.159174         69.238897               8309   
1390  55_55_15_poses.bvh   22.944062         80.771769               9693   
1128  29_29_06_poses.bvh   19.891321         67.013986               8042   

      frame_time_imit  clip_time_imit  num_frames_imit  success  \
1403         0.008333       69.197232             8304    False   
1390         0.008333       80.796768             9696    False   
1128         0.008333       66.997320             8040    False   

      frame_imit_starts  RootJoint_MPE  ...  lTorso_Clavicle_MRE  \
1403               4280       0.371346  ...             0.164160   
1390               4318       2.312106  ...             0.114385   
1128               5646       0.045096  ...             0.186659   

      lShoulder_MRE  lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  \
1403       0.407181    4.648902    0.318670             0.158912   
1390       0.209858    0.347389    0.157804             0.103937   
1128       0.425600    1.062945    0.514637             0.168441   

      rShoulder_MRE  rElbow_MRE  rWrist_MRE     MPJPE     MPJRE  
1403       0.338232    3.082375    0.336588  0.054078  0.636402  
1390       0.246440    0.246450    0.099155  0.149448  0.413330  
1128       0.329481    1.255304    0.523333  0.029415  0.283701  

[3 rows x 51 columns]

In [31]:
display(CMU[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(CMU[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(CMU[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max        8.387581  1.944579e-07   0.422705    0.744230       0.762570   
mean       0.569543  4.610130e-08   0.070050    0.108506       0.120989   
min        0.000349  1.382246e-08   0.007022    0.012553       0.019405   
std        0.750079  2.069331e-08   0.054357    0.087475       0.092811   
50%        0.256737  4.277723e-08   0.049654    0.073240       0.084985   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   2.038462e-07   0.477849    0.733797       0.830772   
mean  4.621502e-08   0.069834    0.106217       0.117329   
min   1.409751e-08   0.006286    0.009991       0.012507   
std   2.087681e-08   0.053409    0.081677       0.088028   
50%   4.271436e-08   0.050255    0.072822       0.082501   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           1.973094e-07             0.118879        0.404759   
mean          5.238451e-08             0.016896        0.044744   
min           1.749358e-08             0.001648        0.004203   
std           1.903763e-08             0.010960        0.038915   
50%           4.752766e-08             0.014376        0.032181   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.276700       0.263932    0.581225    0.836312   
mean             0.031212       0.038446    0.091314    0.126551   
min              0.004408       0.004181    0.014640    0.017878   
std              0.025672       0.030363    0.059608    0.100094   
50%              0.023425       0.028071    0.071122    0.088796   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.277555       0.297640    0.416631    0.654475  
mean             0.031201       0.038307    0.091342    0.123100  
min              0.004396       0.004472    0.012181    0.010847  
std              0.025673       0.029812    0.057570    0.102101  
50%              0.023438       0.028422    0.070987    0.081961

max     RootJoint_MPE
mean    RootJoint_MPE
min     lToeJoint_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max                 lHip_MPE
mean                lHip_MPE
min                 lHip_MPE
std     pelvis_lowerback_MPE
50%                 rHip_MPE
dtype: object

In [32]:
display(CMU[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(CMU[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(CMU[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        8.091123  2.146699   1.994609    1.412196       0.616967  1.919598   
mean       1.956641  0.236842   0.317215    0.255159       0.113204  0.229734   
min        0.001280  0.003467   0.000652    0.002546       0.000074  0.003710   
std        1.895049  0.216338   0.223620    0.176426       0.097025  0.203189   
50%        1.451352  0.171400   0.264558    0.204156       0.089481  0.167994   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    2.065383    1.394240       0.892212              1.594500   
mean   0.299672    0.247740       0.114076              0.176056   
min    0.000333    0.001784       0.000626              0.001288   
std    0.219705    0.165458       0.094967              0.157044   
50%    0.242034    0.202168       0.091930              0.130473   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              1.277367        1.409882             1.395011       1.982065   
mean             0.151152        0.244787             0.186690       0.309740   
min              0.003458        0.003525             0.003891       0.006441   
std              0.126139        0.149191             0.130102       0.179330   
50%              0.115651        0.210600             0.152655       0.272086   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     8.352402    1.818862             1.123800       2.709083    8.323495   
mean    1.167737    0.295540             0.185107       0.312714    1.182155   
min     0.001221    0.008447             0.003689       0.004634    0.003878   
std     1.386233    0.213201             0.125115       0.181934    1.346471   
50%     0.571458    0.231000             0.153663       0.271191    0.614619   

      rWrist_MRE  
max     1.571281  
mean    0.305197  
min     0.003190  
std     0.224032  
50%     0.239087

max        lElbow_MRE
mean    RootJoint_MRE
min        lWrist_MRE
std     RootJoint_MRE
50%     RootJoint_MRE
dtype: object

max     lToeJoint_MRE
mean    lToeJoint_MRE
min     lToeJoint_MRE
std     rToeJoint_MRE
50%     lToeJoint_MRE
dtype: object

In [33]:
display(CMU.sort_values(by=['MPJPE']).head(3)['file_name'])
display(CMU.sort_values(by=['MPJPE']).tail(3)['file_name'])

1545      74_74_09_poses.bvh
1963      89_89_02_poses.bvh
389     118_118_31_poses.bvh
Name: file_name, dtype: object

5        01_01_07_poses.bvh
505    125_125_03_poses.bvh
935    144_144_02_poses.bvh
Name: file_name, dtype: object

In [34]:
display(CMU.sort_values(by=['MPJRE']).head(3)['file_name'])
display(CMU.sort_values(by=['MPJRE']).tail(3)['file_name'])

1501    64_64_13_poses.bvh
1343    49_49_17_poses.bvh
1500    64_64_12_poses.bvh
Name: file_name, dtype: object

325     113_113_22_poses.bvh
1602      77_77_17_poses.bvh
776     139_139_17_poses.bvh
Name: file_name, dtype: object

In [35]:
print("Success: {} out of {}".format(np.sum(CMU['success'] == True), len(CMU)))
print("Success %: {}".format(np.sum(CMU['success'] == True)/len(CMU) * 100))


Success: 22 out of 2075
Success %: 1.0602409638554215


### Investigation Summary

Has some non matching imitation due to physic constraints -> make it hard to really evaluate.

Maximum mean position error: Nothing new


Maximum mean rotation error: has trouble with getting up (balancing)
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: toe joints <br>

similar issue with elbow, wrist, toe and ankles.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (only 22 / 2075).

## DanceDB

In [36]:
DanceDB['MPJPE'] = DanceDB[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
DanceDB['MPJRE'] = DanceDB[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [37]:
DanceDB.loc[:, ~DanceDB.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max    76.426876        280.730437       33689.000000     8.333000e-03   
mean   23.722259         82.135985        9856.712418     8.333000e-03   
min     3.660864          0.624975          75.000000     8.333000e-03   
std    15.429491         58.844138        7061.578966     5.221261e-18   
50%    25.723155         88.479794       10618.000000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max       280.588776     33672.000000        1796.000000  1.751788  0.864331  
mean       82.071227      9848.941176          55.660131  0.130365  0.582772  
min         0.599976        72.000000           0.000000  0.035867  0.107198  
std        58.851090      7062.413241         180.597297  0.137990  0.101132  
50%        88.396464     10608.000000          16.000000  0.112159  0.572007

In [38]:
display(DanceDB.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  \
84  20150927_VasoAristeidou_Vasso_Neutral_v4_01_po...    6.008083   
4   20120805_VasoAristeidou_Vaso_Aristeidou_Zeimpe...   51.163962   
32  20131001_SophieKamenou_Sophie_Bored_C3D_poses.bvh   23.678733   

    clip_time_origin  num_frames_origin  frame_time_imit  clip_time_imit  \
84         18.149274               2178         0.008333       17.999280   
4         190.584043              22871         0.008333      190.592376   
32         79.805141               9577         0.008333       79.796808   

    num_frames_imit  success  frame_imit_starts  RootJoint_MPE  ...  \
84             2160    False                508       1.073488  ...   
4             22872    False               1036       2.032471  ...   
32             9576    False               1796       1.177287  ...   

    lTorso_Clavicle_MRE  lShoulder_MRE  lElbow_MRE  lWrist_MRE  \
84             0.154683       0.364453    1.163793    0.311580   
4              0.178110       0.417413    1.074458    0.415619   
32             0.258553       0.299012    0.824714    0.797340   

    rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  rWrist_MRE     MPJPE  \
84             0.155188       0.324196    0.761970    0.299295  0.105906   
4              0.130584       0.344400    0.366300    0.342570  0.154407   
32             0.192496       0.336177    0.924716    0.595677  0.111482   

       MPJRE  
84  0.522747  
4   0.565658  
32  0.500926  

[3 rows x 51 columns]

In [39]:
display(DanceDB[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(DanceDB[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(DanceDB[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max       33.509082  8.425842e-07   0.144851    0.232330       0.255755   
mean       1.490491  5.535526e-08   0.064849    0.108572       0.122243   
min        0.015877  3.001052e-08   0.033996    0.054849       0.065957   
std        2.707207  6.537730e-08   0.017038    0.028480       0.029761   
50%        1.158877  4.624022e-08   0.062215    0.105856       0.118488   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   8.434127e-07   0.128684    0.206670       0.224321   
mean  5.545998e-08   0.063421    0.101852       0.116386   
min   2.831960e-08   0.032221    0.052865       0.062416   
std   6.543499e-08   0.017328    0.026415       0.027355   
50%   4.652601e-08   0.061812    0.099438       0.113340   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           8.513577e-07             0.032615        0.083862   
mean          5.768971e-08             0.016598        0.038193   
min           3.492526e-08             0.004371        0.013807   
std           6.588230e-08             0.005096        0.011032   
50%           4.918021e-08             0.015752        0.037531   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.056206       0.068075    0.145252    0.214204   
mean             0.026678       0.033148    0.078050    0.103705   
min              0.005771       0.015683    0.034990    0.042701   
std              0.007507       0.009152    0.020016    0.028934   
50%              0.026294       0.032332    0.079418    0.101904   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.056213       0.065477    0.139410    0.183278  
mean             0.026673       0.034218    0.079138    0.103079  
min              0.005841       0.012587    0.037078    0.044246  
std              0.007509       0.008846    0.020145    0.028558  
50%              0.026277       0.034260    0.078764    0.102934

max     RootJoint_MPE
mean    RootJoint_MPE
min     lToeJoint_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max     lHip_MPE
mean    lHip_MPE
min     rHip_MPE
std     lHip_MPE
50%     lHip_MPE
dtype: object

In [40]:
display(DanceDB[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(DanceDB[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(DanceDB[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        6.352005  0.457776   0.661573    0.939396       0.555921  0.399575   
mean       3.696831  0.219456   0.353628    0.398368       0.302066  0.202628   
min        0.286047  0.048626   0.071218    0.067797       0.029236  0.121233   
std        1.004497  0.052025   0.088184    0.116909       0.092680  0.049709   
50%        3.598847  0.214028   0.334742    0.389693       0.302860  0.191497   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    0.580028    0.689065       0.904632              0.342076   
mean   0.351811    0.394309       0.412368              0.154225   
min    0.159644    0.146298       0.061929              0.015949   
std    0.083299    0.097831       0.173356              0.042993   
50%    0.335050    0.387337       0.391883              0.148912   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              0.292177        0.581263             0.359925       0.608794   
mean             0.150583        0.352948             0.235793       0.382075   
min              0.019872        0.012163             0.035599       0.098194   
std              0.038865        0.097372             0.050614       0.078904   
50%              0.143835        0.370224             0.236285       0.377874   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     3.865254    0.997160             0.424381       0.651781    4.037900   
mean    1.145448    0.552943             0.213265       0.388377    1.197666   
min     0.183658    0.080035             0.028623       0.085448    0.220368   
std     0.672055    0.159882             0.057123       0.079004    0.740359   
50%     1.052953    0.561396             0.208393       0.390525    1.054963   

      rWrist_MRE  
max     0.938141  
mean    0.550654  
min     0.031449  
std     0.156149  
50%     0.556015

max     RootJoint_MRE
mean    RootJoint_MRE
min     RootJoint_MRE
std     RootJoint_MRE
50%     RootJoint_MRE
dtype: object

max     lowerback_torso_MRE
mean    lowerback_torso_MRE
min          torso_head_MRE
std     lowerback_torso_MRE
50%     lowerback_torso_MRE
dtype: object

In [41]:
display(DanceDB.sort_values(by=['MPJPE']).head(3)['file_name'])
display(DanceDB.sort_values(by=['MPJPE']).tail(3)['file_name'])

25     20131001_OliviaKyriakides_Olivia_Mix_C3D_poses...
142    20180501_AndreasdelaVara_ANDREAS_Zaloggo_poses...
18      20130216_AnnaCharalambous_Anna_Sad_C3D_poses.bvh
Name: file_name, dtype: object

40     20131001_TheodoraTsiakka_Theodora_Miserable_C3...
145            20180501_CliodelaVara_CLIO_Kolo_poses.bvh
24     20131001_OliviaKyriakides_Olivia_Miserable_C3D...
Name: file_name, dtype: object

In [42]:
display(DanceDB.sort_values(by=['MPJRE']).head(3)['file_name'])
display(DanceDB.sort_values(by=['MPJRE']).tail(3)['file_name'])

25     20131001_OliviaKyriakides_Olivia_Mix_C3D_poses...
130    20151003_ElenaKyriakou_Elena_Relaxed_v1_C3D_po...
131    20151003_ElenaKyriakou_Elena_Relaxed_v2_C3D_po...
Name: file_name, dtype: object

41     20131001_TheodoraTsiakka_Theodora_Mix_C3D_pose...
31     20131001_SophieKamenou_Sophie_Afraid_C3D_poses...
113    20151003_ElenaKyriakou_Elena_Afraid_v1_C3D_pos...
Name: file_name, dtype: object

In [43]:
print("Success: {} out of {}".format(np.sum(DanceDB['success'] == True), len(DanceDB)))
print("Success %: {}".format(np.sum(DanceDB['success'] == True)/len(DanceDB) * 100))


Success: 0 out of 153
Success %: 0.0


### Investigation Summary

Again issues with using hand as a anchor for movements. (Dataset issue?)
In general using non feet for anchor or forces fails. Able to deal with flickering in the ground truth motion.

Maximum mean position error: no major issues not mentioned before
<br>


Maximum mean rotation error: no major issues not mentioned before
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: torso and back <br>

similar issue with elbow, wrist, toe and ankles.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (only 0 / 153).

## EKUT

In [44]:
EKUT['MPJPE'] = EKUT[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
EKUT['MPJRE'] = EKUT[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [45]:
EKUT.loc[:, ~EKUT.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max     6.682267         18.020000        1802.000000     8.333000e-03   
mean    3.222986          5.299971         529.997126     8.333000e-03   
min     2.264082          1.770000         177.000000     8.333000e-03   
std     0.586878          2.148216         214.821560     4.516775e-17   
50%     3.155790          4.925000         492.500000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max        17.999280      2160.000000         443.000000  0.280725  0.801982  
mean        5.247491       629.724138          68.910920  0.139711  0.331456  
min         1.799928       216.000000           0.000000  0.022701  0.000000  
std         2.148761       257.861688          72.240078  0.051505  0.133882  
50%         4.799808       576.000000          40.000000  0.141256  0.318699

In [46]:
display(EKUT.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  clip_time_origin  \
299    300_PushStandOpen_18_poses.bvh    3.272218              5.18   
341   300_PushStandTrans_05_poses.bvh    3.827049              7.37   
274  300_PushStandClosed_03_poses.bvh    3.785598              4.44   

     num_frames_origin  frame_time_imit  clip_time_imit  num_frames_imit  \
299                518         0.008333        5.199792              624   
341                737         0.008333        7.399704              888   
274                444         0.008333        4.399824              528   

     success  frame_imit_starts  RootJoint_MPE  ...  lTorso_Clavicle_MRE  \
299    False                415       0.100693  ...             0.067686   
341    False                427       0.089232  ...             0.148821   
274    False                443       0.000000  ...             0.000000   

     lShoulder_MRE  lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  \
299       0.136571    0.118398    0.055386             0.083971   
341       0.331665    0.208642    0.187053             0.146655   
274       0.000000    0.000000    0.000000             0.000000   

     rShoulder_MRE  rElbow_MRE  rWrist_MRE     MPJPE     MPJRE  
299       0.071567    0.132253    0.140470  0.067549  0.214801  
341       0.325882    0.184225    0.240231  0.123378  0.211944  
274       0.000000    0.000000    0.000000  0.045109  0.000000  

[3 rows x 51 columns]

In [47]:
display(EKUT[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(EKUT[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(EKUT[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max        1.857831  8.894216e-08   0.453305    0.594760       0.578997   
mean       0.585365  5.155331e-08   0.172435    0.271220       0.288233   
min        0.000000  1.446076e-08   0.019327    0.022893       0.025144   
std        0.354683  1.590695e-08   0.076238    0.111436       0.110663   
50%        0.571337  5.510672e-08   0.165029    0.279414       0.301760   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   8.983237e-08   0.448417    0.598540       0.581487   
mean  5.164364e-08   0.173380    0.273351       0.290776   
min   1.863770e-08   0.026626    0.025047       0.045200   
std   1.575318e-08   0.080129    0.110946       0.110268   
50%   5.498737e-08   0.162770    0.279606       0.301030   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           9.128063e-08             0.052698        0.163516   
mean          5.833445e-08             0.020371        0.052160   
min           5.550737e-09             0.001280        0.006044   
std           1.335059e-08             0.006273        0.021026   
50%           6.073406e-08             0.019314        0.048606   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.112779       0.100499    0.322316    0.455881   
mean             0.036542       0.044492    0.102674    0.159537   
min              0.011259       0.011279    0.013113    0.013987   
std              0.013750       0.015822    0.050998    0.079657   
50%              0.034721       0.039650    0.087219    0.131729   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.112780       0.097400    0.313621    0.416313  
mean             0.036544       0.045099    0.100073    0.141972  
min              0.011245       0.006814    0.023610    0.021239  
std              0.013741       0.015268    0.047949    0.072646  
50%              0.034741       0.041044    0.089656    0.124974

max     RootJoint_MPE
mean    RootJoint_MPE
min     rToeJoint_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max                 lHip_MPE
mean                lHip_MPE
min            RootJoint_MPE
std     pelvis_lowerback_MPE
50%                 rHip_MPE
dtype: object

In [48]:
display(EKUT[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(EKUT[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(EKUT[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        5.131435  1.272080   2.301982    1.109242       0.579225  1.427217   
mean       1.404615  0.444792   0.611929    0.371086       0.154211  0.449905   
min        0.000000  0.000000   0.000000    0.000000       0.000000  0.000000   
std        0.987781  0.221064   0.462865    0.210294       0.123291  0.230573   
50%        1.145063  0.426103   0.502986    0.326465       0.114324  0.428462   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    2.990009    1.205738       0.571883              0.524149   
mean   0.620712    0.403683       0.143119              0.161730   
min    0.000000    0.000000       0.000000              0.000000   
std    0.502677    0.245813       0.120047              0.076348   
50%    0.493047    0.337948       0.103483              0.152943   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              0.384456        0.445820             0.569116       0.567708   
mean             0.127874        0.149043             0.151552       0.227542   
min              0.000000        0.000000             0.000000       0.000000   
std              0.054265        0.065810             0.086326       0.093822   
50%              0.118509        0.136376             0.127104       0.208765   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     0.816449    0.755338             0.553389       0.532380    0.803363   
mean    0.241611    0.181626             0.148286       0.225121    0.243170   
min     0.000000    0.000000             0.000000       0.000000    0.000000   
std     0.138462    0.106534             0.088031       0.086492    0.140939   
50%     0.207334    0.156121             0.124950       0.222321    0.202430   

      rWrist_MRE  
max     0.630031  
mean    0.167523  
min     0.000000  
std     0.098115  
50%     0.144413

max     RootJoint_MRE
mean    RootJoint_MRE
min     RootJoint_MRE
std     RootJoint_MRE
50%     RootJoint_MRE
dtype: object

max     lowerback_torso_MRE
mean    lowerback_torso_MRE
min           RootJoint_MRE
std     lowerback_torso_MRE
50%           rToeJoint_MRE
dtype: object

In [49]:
display(EKUT.sort_values(by=['MPJPE']).head(3)['file_name'])
display(EKUT.sort_values(by=['MPJPE']).tail(3)['file_name'])

197               265_TPose_poses.bvh
347               300_Tpose_poses.bvh
291    300_PushStandOpen_10_poses.bvh
Name: file_name, dtype: object

112    234_SLPD303_poses.bvh
111    234_SLPD302_poses.bvh
114    234_SLPD305_poses.bvh
Name: file_name, dtype: object

In [50]:
display(EKUT.sort_values(by=['MPJRE']).head(3)['file_name'])
display(EKUT.sort_values(by=['MPJRE']).tail(3)['file_name'])

274      300_PushStandClosed_03_poses.bvh
320    300_PushStandStraight_04_poses.bvh
347                   300_Tpose_poses.bvh
Name: file_name, dtype: object

83      234_SLP204_poses.bvh
114    234_SLPD305_poses.bvh
111    234_SLPD302_poses.bvh
Name: file_name, dtype: object

In [51]:
print("Success: {} out of {}".format(np.sum(EKUT['success'] == True), len(EKUT)))
print("Success %: {}".format(np.sum(EKUT['success'] == True)/len(EKUT) * 100))


Success: 3 out of 348
Success %: 0.8620689655172413


### Investigation Summary


Maximum mean position error: no major issues not mentioned before
<br>


Maximum mean rotation error: no major issues not mentioned before
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: torso and back <br>

For EKUT it is pretty differnet PE does bad on toe and ankles.
Rotation does bad on knee and hips (other's are usually elbow and wrist).
Caused by object / environment based mocap.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (only 3 / 348).

## Eyes

In [52]:
Eyes['MPJPE'] = Eyes[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
Eyes['MPJRE'] = Eyes[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [53]:
Eyes.loc[:, ~Eyes.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max    23.802028         61.547538        8250.000000     8.333000e-03   
mean   10.294989         29.090439        3811.584000     8.333000e-03   
min     4.488584          8.249670         990.000000     8.333000e-03   
std     1.647666          3.778075        1311.662241     9.720934e-17   
50%    10.201082         29.998800        3600.000000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max        61.397544      7368.000000        3253.000000  0.491713  0.916136  
mean       29.076704      3489.344000          74.918667  0.072421  0.424877  
min         8.199672       984.000000           0.000000  0.019296  0.160632  
std         3.788133       454.594121         328.239777  0.047676  0.125636  
50%        29.998800      3600.000000          16.000000  0.055173  0.407498

In [54]:
display(Eyes.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  \
17      aita_gesture_etc-09-scratch-aita_poses.bvh    9.520946   
46  aita_gesture_etc-48-medium drum-aita_poses.bvh   10.476801   
60            aita_pain-01-headache-aita_poses.bvh   10.479181   

    clip_time_origin  num_frames_origin  frame_time_imit  clip_time_imit  \
17           29.9988               3600         0.008333         29.9988   
46           29.9988               3600         0.008333         29.9988   
60           29.9988               3600         0.008333         29.9988   

    num_frames_imit  success  frame_imit_starts  RootJoint_MPE  ...  \
17             3600     True               3167       0.031708  ...   
46             3600     True               3225       0.012340  ...   
60             3600     True               3253       0.013876  ...   

    lTorso_Clavicle_MRE  lShoulder_MRE  lElbow_MRE  lWrist_MRE  \
17             0.253110       0.158201    0.438707    0.308935   
46             0.164331       0.107673    1.453981    0.487162   
60             0.248145       0.190908    1.461853    0.401284   

    rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  rWrist_MRE     MPJPE  \
17             0.199050       0.122662    0.289800    0.318281  0.023181   
46             0.202811       0.368471    1.945538    0.307900  0.019296   
60             0.218777       0.297169    0.487596    0.183539  0.022769   

       MPJRE  
17  0.195656  
46  0.353500  
60  0.309244  

[3 rows x 51 columns]

In [55]:
display(Eyes[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(Eyes[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(Eyes[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max        7.305821  1.607455e-07   0.359582    0.421290       0.421455   
mean       0.523817  3.878263e-08   0.052551    0.074933       0.083281   
min        0.012340  2.217719e-08   0.019386    0.022885       0.026262   
std        0.594733  1.195923e-08   0.030769    0.052261       0.054360   
50%        0.330153  3.624167e-08   0.044106    0.059281       0.067425   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   1.589692e-07   0.375889    0.391156       0.400617   
mean  3.906150e-08   0.050888    0.072616       0.080558   
min   2.414537e-08   0.018954    0.018233       0.023914   
std   1.165985e-08   0.027862    0.043390       0.046087   
50%   3.739848e-08   0.043078    0.061840       0.069365   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           1.593267e-07             0.112088        0.326773   
mean          4.333745e-08             0.015082        0.035054   
min           2.391317e-08             0.004594        0.006688   
std           1.047555e-08             0.008349        0.026396   
50%           4.221109e-08             0.013016        0.029202   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.229384       0.195550    0.340074    0.566974   
mean             0.024856       0.031611    0.080803    0.102697   
min              0.005041       0.004907    0.019411    0.016999   
std              0.017504       0.018255    0.044346    0.072784   
50%              0.020988       0.026993    0.068256    0.080396   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.230670       0.223788    0.373619    0.633643  
mean             0.024849       0.030175    0.073772    0.090876  
min              0.004991       0.009395    0.016348    0.020825  
std              0.017522       0.018453    0.041417    0.073238  
50%              0.020977       0.025978    0.061478    0.068252

max     RootJoint_MPE
mean    RootJoint_MPE
min     lToeJoint_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max                 rHip_MPE
mean                lHip_MPE
min                 lHip_MPE
std     pelvis_lowerback_MPE
50%                 lHip_MPE
dtype: object

In [56]:
display(Eyes[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(Eyes[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(Eyes[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        7.111422  0.965349   1.178088    1.065071       0.558208  1.023551   
mean       2.400145  0.197085   0.231579    0.223357       0.059548  0.189378   
min        0.146264  0.026094   0.061939    0.081839       0.006199  0.021585   
std        1.413863  0.085895   0.110144    0.116879       0.046566  0.081174   
50%        2.350563  0.180231   0.208307    0.194853       0.049200  0.177188   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    1.143978    1.310170       0.318958              1.268091   
mean   0.230227    0.226294       0.056568              0.160175   
min    0.054088    0.052071       0.001261              0.040383   
std    0.099681    0.100178       0.040471              0.088349   
50%    0.210686    0.207829       0.049642              0.144286   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              0.638994        0.741235             0.557528       0.992125   
mean             0.154496        0.242694             0.232601       0.347111   
min              0.048842        0.086583             0.085046       0.056468   
std              0.069477        0.082569             0.079234       0.127287   
50%              0.140375        0.232178             0.219109       0.324691   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     4.541571    1.307573             0.598902       0.869357    5.097853   
mean    1.027323    0.400893             0.195726       0.338302    1.189100   
min     0.109558    0.078273             0.072823       0.059855    0.122008   
std     0.897412    0.178128             0.068464       0.121054    1.047843   
50%     0.678675    0.360516             0.185214       0.315105    0.739924   

      rWrist_MRE  
max     1.254221  
mean    0.394939  
min     0.102954  
std     0.164278  
50%     0.366157

max     RootJoint_MRE
mean    RootJoint_MRE
min     RootJoint_MRE
std     RootJoint_MRE
50%     RootJoint_MRE
dtype: object

max     rToeJoint_MRE
mean    rToeJoint_MRE
min     rToeJoint_MRE
std     rToeJoint_MRE
50%     lToeJoint_MRE
dtype: object

In [57]:
display(Eyes.sort_values(by=['MPJPE']).head(3)['file_name'])
display(Eyes.sort_values(by=['MPJPE']).tail(3)['file_name'])

46    aita_gesture_etc-48-medium drum-aita_poses.bvh
64              aita_pose-03-open leg-aita_poses.bvh
60              aita_pain-01-headache-aita_poses.bvh
Name: file_name, dtype: object

83     aita_sitdown_standup-11-one knee drawn up-aita...
675    takiguchi_gesture_etc-20-swing chair-takiguchi...
512    kawaguchi_sitdown_standup-01-impolite-kawaguch...
Name: file_name, dtype: object

In [58]:
display(Eyes.sort_values(by=['MPJRE']).head(3)['file_name'])
display(Eyes.sort_values(by=['MPJRE']).tail(3)['file_name'])

694    takiguchi_pose-01-normal-takiguchi_poses.bvh
504    kawaguchi_pose-01-normal-kawaguchi_poses.bvh
23           aita_gesture_etc-18-eat-aita_poses.bvh
Name: file_name, dtype: object

109      aita_walk-11-baggage on the head-aita_poses.bvh
288        ichige_pose-12-body building-ichige_poses.bvh
674    takiguchi_gesture_etc-10-snip nail-takiguchi_p...
Name: file_name, dtype: object

In [59]:
print("Success: {} out of {}".format(np.sum(Eyes['success'] == True), len(Eyes)))
print("Success %: {}".format(np.sum(Eyes['success'] == True)/len(Eyes) * 100))


Success: 3 out of 750
Success %: 0.4


### Investigation Summary

Maximum mean position error: again, issue with using other joints rather than toes on the ground (just kneeling even). Interesting case study for imitating sitting on a chair, the humanoid is able to balance on the toes without falling, albet it does fall backward slowly but adjusts each time. Similar with sitting on one leg. Seems like overfitted on leg power basically.
<br>


Maximum mean rotation error: no major issues not mentioned before
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: torso and back <br>

For position, Elbow, wrist, ankles and knees perform badly.
For Rotation,  elbow and wrist.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (only 3 / 750).

## MPI_HDM05

In [60]:
MPI_HDM05['MPJPE'] = MPI_HDM05[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
MPI_HDM05['MPJRE'] = MPI_HDM05[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [61]:
MPI_HDM05.loc[:, ~MPI_HDM05.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max    39.155376        134.469621       16137.000000     8.333000e-03   
mean   13.053368         40.334162        4840.293023     8.333000e-03   
min     1.998662          0.824967          99.000000     8.333000e-03   
std     6.216501         22.603826        2712.567650     2.608158e-17   
50%    11.725728         34.981934        4198.000000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max       134.394624     16128.000000        3282.000000  1.076068  0.891253  
mean       40.280249      4833.823256          90.632558  0.087431  0.489307  
min         0.799968        96.000000           0.000000  0.033561  0.056981  
std        22.596573      2711.697269         275.930727  0.078671  0.130505  
50%        34.998600      4200.000000          19.000000  0.071104  0.481864

In [62]:
display(MPI_HDM05.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  clip_time_origin  \
100  dg_HDM_dg_05-02_01_120_poses.bvh   10.074627         20.565844   
111  dg_HDM_dg_06-04_01_120_poses.bvh   10.224973         33.223671   
192  tr_HDM_tr_03-04_01_120_poses.bvh   15.174151         51.989587   

     num_frames_origin  frame_time_imit  clip_time_imit  num_frames_imit  \
100               2468         0.008333       20.599176             2472   
111               3987         0.008333       33.198672             3984   
192               6239         0.008333       51.997920             6240   

     success  frame_imit_starts  RootJoint_MPE  ...  lTorso_Clavicle_MRE  \
100    False                990       0.135080  ...             0.246018   
111    False               1099       0.811514  ...             0.161741   
192    False               3282       0.652522  ...             0.230453   

     lShoulder_MRE  lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  \
100       0.325541    0.631533    0.905904             0.205351   
111       0.347748    2.398347    0.452044             0.173921   
192       0.814978    0.977819    0.306354             0.195538   

     rShoulder_MRE  rElbow_MRE  rWrist_MRE     MPJPE     MPJRE  
100       0.389975    0.891524    0.522920  0.057216  0.369463  
111       0.364986    1.522500    0.500139  0.086712  0.664354  
192       0.944644    0.891978    0.602642  0.081260  0.425594  

[3 rows x 51 columns]

In [63]:
display(MPI_HDM05[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(MPI_HDM05[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(MPI_HDM05[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max       18.270198  4.694922e-07   0.197368    0.329394       0.339122   
mean       0.835797  4.977815e-08   0.057004    0.085803       0.096866   
min        0.036114  2.464221e-08   0.029393    0.033190       0.044645   
std        1.341450  3.194297e-08   0.024230    0.046934       0.048797   
50%        0.581703  4.506746e-08   0.049161    0.069234       0.079250   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   4.589504e-07   0.251143    0.314376       0.329333   
mean  5.029243e-08   0.054903    0.080621       0.089236   
min   2.401534e-08   0.022846    0.037100       0.044828   
std   3.135654e-08   0.028850    0.042919       0.045560   
50%   4.668803e-08   0.047646    0.066145       0.073756   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           4.769934e-07             0.045327        0.160488   
mean          5.627889e-08             0.013283        0.036063   
min           2.753322e-08             0.004232        0.015847   
std           3.163559e-08             0.005655        0.018579   
50%           5.149069e-08             0.011658        0.031271   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.106080       0.113709    0.217419    0.346916   
mean             0.024736       0.027668    0.066807    0.078877   
min              0.011275       0.013665    0.039312    0.035282   
std              0.012320       0.013084    0.023732    0.041896   
50%              0.021253       0.023365    0.059691    0.065356   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.106096       0.120526    0.179924    0.283186  
mean             0.024732       0.029892    0.066102    0.080234  
min              0.011265       0.013681    0.020814    0.024558  
std              0.012322       0.012914    0.023992    0.039605  
50%              0.021274       0.026514    0.063683    0.069891

max     RootJoint_MPE
mean    RootJoint_MPE
min     rToeJoint_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max     rHip_MPE
mean    lHip_MPE
min     rHip_MPE
std     rHip_MPE
50%     lHip_MPE
dtype: object

In [64]:
display(MPI_HDM05[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(MPI_HDM05[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(MPI_HDM05[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        7.897886  0.591427   1.983975    0.734057       0.351644  0.717903   
mean       3.743015  0.211925   0.294205    0.224484       0.090057  0.211009   
min        0.082790  0.057684   0.016867    0.065976       0.010361  0.059856   
std        1.588717  0.075261   0.166904    0.101618       0.055059  0.079315   
50%        3.854919  0.191994   0.247504    0.191037       0.076222  0.196325   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    1.021448    0.588011       0.345450              0.543757   
mean   0.274083    0.221087       0.096872              0.153518   
min    0.018683    0.042835       0.004885              0.040931   
std    0.115102    0.084700       0.051474              0.070672   
50%    0.240203    0.201391       0.086342              0.130891   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              0.440318        0.614643             0.451476       0.814978   
mean             0.140218        0.266792             0.212408       0.320585   
min              0.022441        0.039447             0.061792       0.060626   
std              0.060045        0.088069             0.060034       0.095879   
50%              0.124673        0.258844             0.215382       0.314071   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     4.393248    1.829634             0.452446       0.944644    3.813659   
mean    1.075661    0.414770             0.200768       0.291545    0.952670   
min     0.090915    0.058605             0.035519       0.071901    0.070311   
std     0.814545    0.226788             0.061521       0.099165    0.766412   
50%     0.785102    0.361897             0.197423       0.281645    0.696437   

      rWrist_MRE  
max     1.502440  
mean    0.390477  
min     0.058609  
std     0.190916  
50%     0.358252

max     RootJoint_MRE
mean    RootJoint_MRE
min        lElbow_MRE
std     RootJoint_MRE
50%     RootJoint_MRE
dtype: object

max     rToeJoint_MRE
mean    lToeJoint_MRE
min     rToeJoint_MRE
std     rToeJoint_MRE
50%     lToeJoint_MRE
dtype: object

In [65]:
display(MPI_HDM05.sort_values(by=['MPJPE']).head(3)['file_name'])
display(MPI_HDM05.sort_values(by=['MPJPE']).tail(3)['file_name'])

179    tr_HDM_tr_02-03_02_120_poses.bvh
120    dg_HDM_dg_08-01_01_120_poses.bvh
204    tr_HDM_tr_05-01_02_120_poses.bvh
Name: file_name, dtype: object

203    tr_HDM_tr_04-01_01_120_poses.bvh
42     bk_HDM_bk_04-01_03_120_poses.bvh
212    tr_HDM_tr_05-03_04_120_poses.bvh
Name: file_name, dtype: object

In [66]:
display(MPI_HDM05.sort_values(by=['MPJRE']).head(3)['file_name'])
display(MPI_HDM05.sort_values(by=['MPJRE']).tail(3)['file_name'])

113    dg_HDM_dg_07-01_02_120_poses.bvh
115    dg_HDM_dg_07-01_04_120_poses.bvh
108    dg_HDM_dg_06-03_02_120_poses.bvh
Name: file_name, dtype: object

90     dg_HDM_dg_03-09_03_120_poses.bvh
188    tr_HDM_tr_03-02_04_120_poses.bvh
150    mm_HDM_mm_03-10_06_120_poses.bvh
Name: file_name, dtype: object

In [67]:
print("Success: {} out of {}".format(np.sum(MPI_HDM05['success'] == True), len(MPI_HDM05)))
print("Success %: {}".format(np.sum(MPI_HDM05['success'] == True)/len(MPI_HDM05) * 100))


Success: 0 out of 215
Success %: 0.0


### Investigation Summary

Multiple joints on the ground can have unnatural or overly large forces on the leg.

Maximum mean position error: no major issues not mentioned before
<br>


Maximum mean rotation error: no major issues not mentioned before
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: torso and back <br>

similar issue with elbow, wrist, toe and ankles.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (0).

## MPI_Limits

In [68]:
MPI_Limits['MPJPE'] = MPI_Limits[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
MPI_Limits['MPJRE'] = MPI_Limits[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [69]:
MPI_Limits.loc[:, ~MPI_Limits.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max    23.051260         75.163660        9020.000000     8.333000e-03   
mean   11.701180         35.698334        4283.971429     8.333000e-03   
min     3.672912          7.474701         897.000000     8.333000e-03   
std     4.938810         17.843979        2141.363124     1.760049e-18   
50%    11.949366         37.148514        4458.000000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max        75.196992      9024.000000          56.000000  0.369542  0.771875  
mean       35.632860      4276.114286          11.085714  0.121918  0.548342  
min         7.399704       888.000000           0.000000  0.033942  0.303537  
std        17.850335      2142.125934          13.888996  0.085874  0.121469  
50%        36.998520      4440.000000           6.000000  0.095188  0.518551

In [70]:
display(MPI_Limits.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  clip_time_origin  num_frames_origin  \
14  03100_lar2_poses.bvh   13.003302         36.073557               4329   
13  03100_lar1_poses.bvh   10.669889         35.990227               4319   
16  03100_lar4_poses.bvh   10.874104         37.765156               4532   

    frame_time_imit  clip_time_imit  num_frames_imit  success  \
14         0.008333       35.998560             4320    False   
13         0.008333       35.998560             4320    False   
16         0.008333       37.798488             4536    False   

    frame_imit_starts  RootJoint_MPE  ...  lTorso_Clavicle_MRE  lShoulder_MRE  \
14                 40       1.403148  ...             0.170207       0.272482   
13                 46       1.502964  ...             0.174680       0.465495   
16                 56       0.930746  ...             0.112018       0.283135   

    lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
14    2.730883    0.315454             0.168986       0.274797    1.291490   
13    1.436459    0.328856             0.212932       0.431233    5.491577   
16    5.286219    0.185298             0.095969       0.149115    0.310180   

    rWrist_MRE     MPJPE     MPJRE  
14    0.328024  0.129506  0.607346  
13    0.335730  0.127972  0.771875  
16    0.146279  0.095188  0.607002  

[3 rows x 51 columns]

In [71]:
display(MPI_Limits[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(MPI_Limits[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(MPI_Limits[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max        4.214333  1.075076e-07   0.203929    0.464564       0.492858   
mean       0.956491  4.167115e-08   0.073052    0.135816       0.146298   
min        0.027275  2.583496e-08   0.021248    0.038903       0.044992   
std        0.929400  1.686206e-08   0.044491    0.104840       0.106414   
50%        0.825624  3.883359e-08   0.056729    0.101000       0.094843   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   1.119703e-07   0.339512    0.521153       0.694853   
mean  4.268258e-08   0.084020    0.134818       0.155659   
min   2.726747e-08   0.023425    0.021534       0.035031   
std   1.770284e-08   0.074605    0.122845       0.153498   
50%   4.038279e-08   0.060842    0.093539       0.099395   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           1.144365e-07             0.062502        0.253931   
mean          4.905985e-08             0.016623        0.066124   
min           3.144325e-08             0.005794        0.017018   
std           1.578520e-08             0.014482        0.064493   
50%           4.372934e-08             0.011329        0.043605   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.168131       0.165139    0.273117    0.413028   
mean             0.042766       0.052068    0.095613    0.131948   
min              0.010728       0.015939    0.041415    0.052121   
std              0.042106       0.041259    0.058162    0.097989   
50%              0.027078       0.039824    0.080338    0.103254   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.168225       0.221185    0.374447    0.570312  
mean             0.042779       0.052395    0.103372    0.148516  
min              0.010743       0.015422    0.046882    0.067411  
std              0.042175       0.051370    0.076853    0.121130  
50%              0.026907       0.034690    0.073269    0.098146

max     RootJoint_MPE
mean    RootJoint_MPE
min        rWrist_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max                 lHip_MPE
mean                lHip_MPE
min                 lHip_MPE
std     pelvis_lowerback_MPE
50%                 lHip_MPE
dtype: object

In [72]:
display(MPI_Limits[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(MPI_Limits[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(MPI_Limits[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        5.348074  0.688743   1.105227    0.907575       0.235247  0.830541   
mean       2.635859  0.251941   0.418233    0.366591       0.068018  0.316077   
min        0.680608  0.070196   0.072142    0.117006       0.017456  0.098539   
std        1.082181  0.152646   0.287319    0.235877       0.048393  0.221620   
50%        2.562290  0.234384   0.351481    0.272384       0.056241  0.213049   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    1.035083    0.883792       0.208373              0.672184   
mean   0.357307    0.406157       0.065194              0.206130   
min    0.091978    0.096337       0.012540              0.073742   
std    0.213320    0.262264       0.047979              0.166297   
50%    0.338805    0.262162       0.054559              0.142628   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              0.391429        0.638938             0.667881       0.928303   
mean             0.175706        0.307344             0.296166       0.383473   
min              0.068106        0.166625             0.111231       0.197191   
std              0.089191        0.114717             0.130343       0.157929   
50%              0.139406        0.279136             0.270173       0.356681   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     5.286219    1.214973             0.718888       0.818700    5.491577   
mean    1.472110    0.513578             0.296330       0.401566    1.420545   
min     0.234790    0.185298             0.095969       0.123826    0.279726   
std     1.424079    0.268255             0.141477       0.170721    1.411120   
50%     0.735556    0.431953             0.251498       0.403991    0.743860   

      rWrist_MRE  
max     1.433748  
mean    0.608511  
min     0.146279  
std     0.326103  
50%     0.489374

max        rElbow_MRE
mean    RootJoint_MRE
min     RootJoint_MRE
std        lElbow_MRE
50%     RootJoint_MRE
dtype: object

max     rToeJoint_MRE
mean    rToeJoint_MRE
min     rToeJoint_MRE
std     rToeJoint_MRE
50%     rToeJoint_MRE
dtype: object

In [73]:
display(MPI_Limits.sort_values(by=['MPJPE']).head(3)['file_name'])
display(MPI_Limits.sort_values(by=['MPJPE']).tail(3)['file_name'])

21    03100_uar3_poses.bvh
23    03100_uar5_poses.bvh
22    03100_uar4_poses.bvh
Name: file_name, dtype: object

8       03099_op4_poses.bvh
30    03101_ulr1c_poses.bvh
31    03101_ulr1d_poses.bvh
Name: file_name, dtype: object

In [74]:
display(MPI_Limits.sort_values(by=['MPJRE']).head(3)['file_name'])
display(MPI_Limits.sort_values(by=['MPJRE']).tail(3)['file_name'])

10     03099_op7_poses.bvh
26    03101_uar5_poses.bvh
23    03100_uar5_poses.bvh
Name: file_name, dtype: object

9      03099_op5_poses.bvh
12     03099_op9_poses.bvh
13    03100_lar1_poses.bvh
Name: file_name, dtype: object

In [75]:
print("Success: {} out of {}".format(np.sum(MPI_Limits['success'] == True), len(MPI_Limits)))
print("Success %: {}".format(np.sum(MPI_Limits['success'] == True)/len(MPI_Limits) * 100))


Success: 0 out of 35
Success %: 0.0


### Investigation Summary

Maximum mean position error: Although sitting in the air seems to be balanceable, standing on one leg and raising another is not.
<br>


Maximum mean rotation error: no major issues not mentioned before
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: torso and back <br>

similar issue with elbow, wrist, toe and ankles.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (0).

## MPI_mosh

In [76]:
MPI_mosh['MPJPE'] = MPI_mosh[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
MPI_mosh['MPJRE'] = MPI_mosh[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [77]:
MPI_mosh.loc[:, ~MPI_mosh.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max    11.904076         32.870000        3287.000000     8.333000e-03   
mean    5.551035         12.878148        1412.857143     8.333000e-03   
min     2.575367          3.620000         362.000000     8.333000e-03   
std     2.134291          6.915065         755.809460     1.746099e-18   
50%     5.332680         11.160000        1134.000000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max        32.798688      3936.000000         218.000000  0.361936  0.904446  
mean       12.820266      1538.493506          21.077922  0.085157  0.462389  
min         3.599856       432.000000           4.000000  0.027262  0.104984  
std         6.929641       831.590243          29.862301  0.059810  0.216681  
50%        11.199552      1344.000000          12.000000  0.063232  0.456783

In [78]:
display(MPI_mosh.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  clip_time_origin  \
48  50020_shake_shoulders_poses.bvh    3.032688          3.620000   
0              00008_misc_poses.bvh    3.836111          8.466328   
10        00058_jiggles 2_poses.bvh    3.613143          6.720000   

    num_frames_origin  frame_time_imit  clip_time_imit  num_frames_imit  \
48                362         0.008333        3.599856              432   
0                1016         0.008333        8.399664             1008   
10                672         0.008333        6.599736              792   

    success  frame_imit_starts  RootJoint_MPE  ...  lTorso_Clavicle_MRE  \
48    False                 91       0.020835  ...             0.306883   
0     False                139       0.088025  ...             0.165591   
10    False                218       0.175380  ...             0.135716   

    lShoulder_MRE  lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  \
48       0.208712    0.796282    0.404347             0.195166       0.179251   
0        0.366557    1.757239    0.996461             0.158162       0.667507   
10       0.189485    4.520486    0.355916             0.164298       0.211576   

    rElbow_MRE  rWrist_MRE     MPJPE     MPJRE  
48    0.517541    0.455347  0.041859  0.259243  
0     2.400441    0.659337  0.038628  0.541802  
10    4.503741    0.335302  0.063301  0.719772  

[3 rows x 51 columns]

In [79]:
display(MPI_mosh[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(MPI_mosh[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(MPI_mosh[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max        2.166465  5.628230e-08   0.312208    0.621158       0.662481   
mean       0.198842  2.899001e-08   0.089340    0.136732       0.147013   
min        0.020835  2.535591e-08   0.019926    0.040516       0.041059   
std        0.266393  3.803847e-09   0.063651    0.101679       0.108389   
50%        0.129454  2.792112e-08   0.058305    0.096751       0.107336   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   5.669761e-08   0.331700    0.465879       0.502705   
mean  2.913222e-08   0.084615    0.129448       0.140109   
min   2.498670e-08   0.015628    0.035961       0.039767   
std   3.924292e-09   0.063887    0.093169       0.099731   
50%   2.817986e-08   0.052886    0.083966       0.093329   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           5.285317e-08             0.051230        0.200285   
mean          3.620675e-08             0.014001        0.051985   
min           2.743254e-08             0.003961        0.012140   
std           4.995254e-09             0.009296        0.044422   
50%           3.592782e-08             0.010336        0.031969   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.128534       0.171711    0.343913    0.505615   
mean             0.034241       0.046302    0.109385    0.167063   
min              0.007327       0.009877    0.016498    0.026305   
std              0.028605       0.037857    0.086534    0.144271   
50%              0.022181       0.027271    0.064291    0.096024   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.128618       0.175237    0.353326    0.535118  
mean             0.034246       0.046346    0.108871    0.164604  
min              0.007338       0.011489    0.020502    0.027681  
std              0.028620       0.038533    0.081864    0.140468  
50%              0.022150       0.030423    0.069787    0.096881

max     RootJoint_MPE
mean    RootJoint_MPE
min     lToeJoint_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max     pelvis_lowerback_MPE
mean                lHip_MPE
min                 rHip_MPE
std                 lHip_MPE
50%                 lHip_MPE
dtype: object

In [80]:
display(MPI_mosh[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(MPI_mosh[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(MPI_mosh[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        5.365139  1.033373   1.148604    0.649633       0.427080  0.840561   
mean       1.784896  0.266265   0.309176    0.233186       0.116830  0.249613   
min        0.168857  0.051948   0.053922    0.050215       0.009122  0.039942   
std        1.188901  0.177422   0.216782    0.102973       0.114515  0.165829   
50%        1.580439  0.207941   0.227394    0.217177       0.062677  0.205962   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    1.153631    0.747695       0.254654              0.653462   
mean   0.277952    0.221131       0.077612              0.163338   
min    0.049282    0.055686       0.004654              0.033499   
std    0.212927    0.109540       0.060777              0.108154   
50%    0.201159    0.208142       0.059026              0.124177   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              0.515116        0.541809             0.628288       0.971230   
mean             0.133280        0.171259             0.205910       0.447718   
min              0.034120        0.032284             0.071948       0.117749   
std              0.074837        0.077172             0.113271       0.178466   
50%              0.126242        0.158403             0.170304       0.433957   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     4.740344    0.996461             0.438819       0.861340    4.776819   
mean    1.672166    0.355196             0.193094       0.399690    1.638155   
min     0.073114    0.069973             0.066287       0.143388    0.046376   
std     1.432567    0.169252             0.101485       0.174644    1.429138   
50%     1.645264    0.328376             0.168786       0.376325    1.478242   

      rWrist_MRE  
max     0.917316  
mean    0.331317  
min     0.086318  
std     0.153161  
50%     0.317368

max     RootJoint_MRE
mean    RootJoint_MRE
min     RootJoint_MRE
std        lElbow_MRE
50%        lElbow_MRE
dtype: object

max     rToeJoint_MRE
mean    rToeJoint_MRE
min     rToeJoint_MRE
std     rToeJoint_MRE
50%     rToeJoint_MRE
dtype: object

In [81]:
display(MPI_mosh.sort_values(by=['MPJPE']).head(3)['file_name'])
display(MPI_mosh.sort_values(by=['MPJPE']).tail(3)['file_name'])

44             50020_neck_poses.bvh
37        50007_stretches_poses.bvh
17    00096_simple_crouch_poses.bvh
Name: file_name, dtype: object

51       50021_army_poses_poses.bvh
60    50022_stretch_poses_poses.bvh
54           50021_misc_9_poses.bvh
Name: file_name, dtype: object

In [82]:
display(MPI_mosh.sort_values(by=['MPJRE']).head(3)['file_name'])
display(MPI_mosh.sort_values(by=['MPJRE']).tail(3)['file_name'])

44                   50020_neck_poses.bvh
69    50026_light_hopping_stiff_poses.bvh
22                   50002_hips_poses.bvh
Name: file_name, dtype: object

21        00111_stretches_poses.bvh
57           50022_misc_1_poses.bvh
20    00111_simple_crouch_poses.bvh
Name: file_name, dtype: object

In [83]:
print("Success: {} out of {}".format(np.sum(MPI_mosh['success'] == True), len(MPI_mosh)))
print("Success %: {}".format(np.sum(MPI_mosh['success'] == True)/len(MPI_mosh) * 100))


Success: 0 out of 77
Success %: 0.0


### Investigation Summary

Maximum mean position error: o major issues not mentioned before
<br>


Maximum mean rotation error: no major issues not mentioned before
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: torso and back <br>

similar issue with elbow, wrist, toe and ankles.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (0).

## SFU (Part of Training Set)

In [84]:
SFU['MPJPE'] = SFU[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
SFU['MPJRE'] = SFU[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [85]:
SFU.loc[:, ~SFU.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max    44.943783        155.902097       18709.000000     8.333000e-03   
mean    7.493016         20.766783        2492.113636     8.333000e-03   
min     2.487641          2.474901         297.000000     8.333000e-03   
std     6.708536         24.187107        2902.568928     3.509557e-18   
50%     5.694251         14.316094        1718.000000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max       155.793768     18696.000000         470.000000  0.447321  0.799276  
mean       20.717353      2486.181818          59.000000  0.135007  0.493692  
min         2.399904       288.000000          22.000000  0.043010  0.212227  
std        24.181299      2901.871916          72.606618  0.091886  0.158414  
50%        14.299428      1716.000000          40.000000  0.093195  0.482436

In [86]:
display(SFU.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  clip_time_origin  \
12      0008_0008_ChaCha001_poses.bvh   17.053938         54.189499   
33  0017_0017_WushuKicks001_poses.bvh    6.705118         19.815874   
11     0007_0007_Walking001_poses.bvh   12.130380         32.798688   

    num_frames_origin  frame_time_imit  clip_time_imit  num_frames_imit  \
12               6503         0.008333       54.197832             6504   
33               2378         0.008333       19.799208             2376   
11               3936         0.008333       32.798688             3936   

    success  frame_imit_starts  RootJoint_MPE  ...  lTorso_Clavicle_MRE  \
12    False                148       0.717321  ...             0.195177   
33    False                204       0.734139  ...             0.161504   
11    False                470       0.863739  ...             0.063321   

    lShoulder_MRE  lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  \
12       0.363273    1.103020    0.444566             0.174324       0.402025   
33       0.326580    1.236125    0.328369             0.148616       0.276751   
11       0.128197    0.151845    0.102836             0.129524       0.136917   

    rElbow_MRE  rWrist_MRE     MPJPE     MPJRE  
12    1.263997    0.435780  0.082909  0.500981  
33    0.429476    0.223003  0.107748  0.536469  
11    0.169241    0.106458  0.077123  0.376550  

[3 rows x 51 columns]

In [87]:
display(SFU[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(SFU[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(SFU[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max        5.433064  1.329379e-07   0.227306    0.424027       0.421397   
mean       1.316908  6.796888e-08   0.079742    0.132508       0.141772   
min        0.223695  3.300846e-08   0.029007    0.055169       0.056859   
std        1.159337  2.587416e-08   0.045037    0.085067       0.087065   
50%        0.864702  6.355935e-08   0.065176    0.108222       0.116877   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   1.371364e-07   0.271367    0.402442       0.435392   
mean  6.789113e-08   0.084543    0.130588       0.141043   
min   3.205119e-08   0.033545    0.051069       0.057412   
std   2.596421e-08   0.058052    0.087844       0.094704   
50%   6.347306e-08   0.063133    0.100494       0.105557   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           1.307329e-07             0.056581        0.361295   
mean          7.038784e-08             0.022228        0.059685   
min           3.030525e-08             0.005853        0.018554   
std           2.550221e-08             0.011390        0.058980   
50%           6.536763e-08             0.018472        0.038819   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.225713       0.217311    0.254495    0.304928   
mean             0.041533       0.045513    0.089544    0.123996   
min              0.013069       0.011337    0.025494    0.043583   
std              0.037105       0.037790    0.053149    0.075148   
50%              0.029114       0.031612    0.069828    0.086244   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.225939       0.217385    0.245024    0.364216  
mean             0.041515       0.046741    0.084214    0.118067  
min              0.013046       0.017798    0.017893    0.047427  
std              0.037113       0.035387    0.054637    0.075624  
50%              0.029129       0.032840    0.061441    0.082452

max     RootJoint_MPE
mean    RootJoint_MPE
min     RootJoint_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max     pelvis_lowerback_MPE
mean                rHip_MPE
min     pelvis_lowerback_MPE
std     pelvis_lowerback_MPE
50%                 rHip_MPE
dtype: object

In [88]:
display(SFU[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(SFU[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(SFU[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        6.006714  0.718761   1.219441    0.872953       0.471226  0.924329   
mean       3.166351  0.267787   0.422701    0.362655       0.186164  0.276040   
min        0.262190  0.127106   0.178019    0.131041       0.056770  0.122482   
std        1.669404  0.122728   0.215763    0.177904       0.094792  0.168767   
50%        3.032194  0.235054   0.369561    0.321952       0.172869  0.196911   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    1.210300    0.893257       0.643392              0.682138   
mean   0.391712    0.298816       0.160457              0.204593   
min    0.112790    0.119433       0.015438              0.060872   
std    0.234120    0.150749       0.105626              0.146935   
50%    0.319882    0.264126       0.144488              0.152593   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              0.624823        0.677049             1.035597       1.875637   
mean             0.178208        0.252448             0.212822       0.372742   
min              0.048076        0.083078             0.052910       0.128197   
std              0.110133        0.116225             0.161386       0.271425   
50%              0.155450        0.243107             0.188632       0.319682   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     3.418691    1.792441             1.242625       1.668855    3.371840   
mean    0.911905    0.395148             0.210905       0.342164    0.878913   
min     0.129122    0.083016             0.049750       0.123802    0.069245   
std     0.803093    0.329267             0.186175       0.236311    0.814559   
50%     0.554604    0.325484             0.178034       0.327341    0.568902   

      rWrist_MRE  
max     1.705608  
mean    0.381318  
min     0.079219  
std     0.336182  
50%     0.299846

max     RootJoint_MRE
mean    RootJoint_MRE
min     RootJoint_MRE
std     RootJoint_MRE
50%     RootJoint_MRE
dtype: object

max     lToeJoint_MRE
mean    rToeJoint_MRE
min     rToeJoint_MRE
std     lToeJoint_MRE
50%     rToeJoint_MRE
dtype: object

In [89]:
display(SFU.sort_values(by=['MPJPE']).head(3)['file_name'])
display(SFU.sort_values(by=['MPJPE']).tail(3)['file_name'])

15     0008_0008_Walking002_poses.bvh
42    0018_0018_XinJiang002_poses.bvh
5     0005_0005_SlowTrot001_poses.bvh
Name: file_name, dtype: object

17       0012_0012_JumpAndRoll001_poses.bvh
26    0017_0017_JumpingOnBench001_poses.bvh
31        0017_0017_SpeedVault001_poses.bvh
Name: file_name, dtype: object

In [90]:
display(SFU.sort_values(by=['MPJRE']).head(3)['file_name'])
display(SFU.sort_values(by=['MPJRE']).tail(3)['file_name'])

38    0018_0018_Moonwalk001_poses.bvh
39      0018_0018_TipToe001_poses.bvh
8      0007_0007_Balance001_poses.bvh
Name: file_name, dtype: object

34                     0018_0018_Bridge001_poses.bvh
40    0018_0018_TraditionalChineseDance001_poses.bvh
42                   0018_0018_XinJiang002_poses.bvh
Name: file_name, dtype: object

In [91]:
print("Success: {} out of {}".format(np.sum(SFU['success'] == True), len(SFU)))
print("Success %: {}".format(np.sum(SFU['success'] == True)/len(SFU) * 100))


Success: 0 out of 44
Success %: 0.0


### Investigation Summary

Maximum mean position error: no major issues not mentioned before
<br>


Maximum mean rotation error: no major issues not mentioned before
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: torso and back <br>

similar issue with elbow, wrist, toe and ankles.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (0).

## Transitions

In [92]:
Transitions['MPJPE'] = Transitions[JOINT_MPE_NAMES].sum(axis=1) / len(JOINT_NAMES)
Transitions['MPJRE'] = Transitions[JOINT_MRE_NAMES].sum(axis=1) / len(JOINT_NAMES)

In [93]:
Transitions.loc[:, ~Transitions.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])].describe().loc[['max', 'mean', 'min', 'std', '50%']]

time_taken  clip_time_origin  num_frames_origin  frame_time_imit  \
max     7.198821         13.224471        1587.000000     8.333000e-03   
mean    3.961273          8.233610         988.072727     8.333000e-03   
min     2.789982          4.566484         548.000000     8.333000e-03   
std     0.735654          1.616668         194.007884     1.219864e-17   
50%     3.868325          8.228838         987.500000     8.333000e-03   

      clip_time_imit  num_frames_imit  frame_imit_starts     MPJPE     MPJRE  
max        13.199472      1584.000000         501.000000  0.142877  0.587964  
mean        8.181491       981.818182          94.172727  0.061564  0.350689  
min         4.599816       552.000000          26.000000  0.028756  0.090128  
std         1.619890       194.394576          93.203128  0.019387  0.093410  
50%         8.199672       984.000000          65.500000  0.057198  0.344486

In [94]:
display(Transitions.sort_values(by=['frame_imit_starts']).tail(3))

file_name  time_taken  \
93  mazen_c3d_twistdance_jumpingtwist360_poses.bvh    4.128920   
98         mazen_c3d_walkbackwards_stand_poses.bvh    3.909580   
68            mazen_c3d_punchboxing_push_poses.bvh    3.106721   

    clip_time_origin  num_frames_origin  frame_time_imit  clip_time_imit  \
93          7.074717                849         0.008333        6.999720   
98          7.874685                945         0.008333        7.799688   
68          5.516446                662         0.008333        5.399784   

    num_frames_imit  success  frame_imit_starts  RootJoint_MPE  ...  \
93              840    False                496       0.088665  ...   
98              936    False                498       0.115595  ...   
68              648    False                501       0.056748  ...   

    lTorso_Clavicle_MRE  lShoulder_MRE  lElbow_MRE  lWrist_MRE  \
93             0.111918       0.161493    0.244176    0.245385   
98             0.083863       0.195673    0.205100    0.193008   
68             0.053426       0.095147    0.162079    0.066698   

    rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  rWrist_MRE     MPJPE  \
93             0.100761       0.117265    0.732951    0.738758  0.040013   
98             0.109281       0.116751    0.263274    0.169788  0.034793   
68             0.053564       0.127121    0.093048    0.129219  0.028756   

       MPJRE  
93  0.257748  
98  0.200015  
68  0.090128  

[3 rows x 51 columns]

In [95]:
display(Transitions[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(Transitions[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(Transitions[JOINT_MPE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  lToeJoint_MPE  \
max        1.559771  7.308492e-08   0.137132    0.236237       0.254154   
mean       0.394901  3.832035e-08   0.050904    0.080498       0.088845   
min        0.056748  2.444106e-08   0.031499    0.048281       0.055831   
std        0.292047  9.452240e-09   0.014844    0.021685       0.023435   
50%        0.320681  3.539646e-08   0.048752    0.077930       0.086479   

          rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  \
max   7.671512e-08   0.090900    0.212428       0.235797   
mean  3.847199e-08   0.048666    0.077197       0.084858   
min   2.363246e-08   0.031251    0.045360       0.045376   
std   9.764874e-09   0.011056    0.020798       0.023356   
50%   3.489440e-08   0.047197    0.074362       0.081049   

      pelvis_lowerback_MPE  lowerback_torso_MPE  torso_head_MPE  \
max           7.971147e-08             0.035835        0.105048   
mean          4.522591e-08             0.014399        0.034313   
min           3.027499e-08             0.003222        0.017611   
std           9.313214e-09             0.005662        0.010827   
50%           4.262750e-08             0.013506        0.032875   

      lTorso_Clavicle_MPE  lShoulder_MPE  lElbow_MPE  lWrist_MPE  \
max              0.070682       0.071600    0.110704    0.160263   
mean             0.024543       0.023281    0.055936    0.079015   
min              0.010581       0.011648    0.018519    0.038761   
std              0.007612       0.007573    0.011422    0.015768   
50%              0.023617       0.022479    0.055065    0.077370   

      rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  rWrist_MPE  
max              0.070638       0.072811    0.093648    0.155860  
mean             0.024501       0.024686    0.056375    0.068353  
min              0.010463       0.011217    0.020090    0.037444  
std              0.007618       0.008669    0.011316    0.017489  
50%              0.023595       0.023038    0.056499    0.065021

max     RootJoint_MPE
mean    RootJoint_MPE
min     RootJoint_MPE
std     RootJoint_MPE
50%     RootJoint_MPE
dtype: object

max                 lHip_MPE
mean                lHip_MPE
min                 rHip_MPE
std     pelvis_lowerback_MPE
50%                 rHip_MPE
dtype: object

In [96]:
display(Transitions[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']])
display(Transitions[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmax(axis=1))
display(Transitions[JOINT_MRE_NAMES].describe().loc[['max', 'mean', 'min', 'std', '50%']].idxmin(axis=1))

RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  lToeJoint_MRE  rHip_MRE  \
max        4.260858  0.445030   0.741760    0.531327       0.753656  0.379356   
mean       1.804975  0.203475   0.283225    0.231711       0.145303  0.193949   
min        0.221252  0.064695   0.063934    0.124786       0.003489  0.086740   
std        0.850333  0.054489   0.093077    0.084339       0.127239  0.056110   
50%        1.699494  0.200736   0.267811    0.208650       0.112210  0.182116   

      rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  pelvis_lowerback_MRE  \
max    0.592246    0.683216       0.634633              0.447594   
mean   0.276038    0.245580       0.125703              0.168731   
min    0.131977    0.113791       0.043014              0.046143   
std    0.076383    0.083972       0.087999              0.074533   
50%    0.255849    0.226269       0.101233              0.148796   

      lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
max              0.460334        0.475255             0.302616       0.746956   
mean             0.177832        0.206188             0.147620       0.273934   
min              0.046087        0.047655             0.053426       0.095147   
std              0.079190        0.077452             0.047117       0.092211   
50%              0.161008        0.189116             0.139215       0.263308   

      lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
max     3.010381    0.633399             0.559976       0.537362    3.549272   
mean    0.886644    0.295190             0.149300       0.258555    0.633920   
min     0.143626    0.066698             0.053564       0.111679    0.093048   
std     0.647721    0.105205             0.068844       0.095256    0.497350   
50%     0.625451    0.271905             0.133302       0.240043    0.471266   

      rWrist_MRE  
max     0.792308  
mean    0.305915  
min     0.123712  
std     0.149159  
50%     0.257189

max     RootJoint_MRE
mean    RootJoint_MRE
min     RootJoint_MRE
std     RootJoint_MRE
50%     RootJoint_MRE
dtype: object

max     lTorso_Clavicle_MRE
mean          rToeJoint_MRE
min           lToeJoint_MRE
std     lTorso_Clavicle_MRE
50%           rToeJoint_MRE
dtype: object

In [97]:
display(Transitions.sort_values(by=['MPJPE']).head(3)['file_name'])
display(Transitions.sort_values(by=['MPJPE']).tail(3)['file_name'])

68       mazen_c3d_punchboxing_push_poses.bvh
98    mazen_c3d_walkbackwards_stand_poses.bvh
5       mazen_c3d_JOOF_turntwist180_poses.bvh
Name: file_name, dtype: object

80        mazen_c3d_run_longjump_poses.bvh
0             mazen_c3d_GUS_kick_poses.bvh
8     mazen_c3d_LOB_turntwist180_poses.bvh
Name: file_name, dtype: object

In [98]:
display(Transitions.sort_values(by=['MPJRE']).head(3)['file_name'])
display(Transitions.sort_values(by=['MPJRE']).tail(3)['file_name'])

68       mazen_c3d_punchboxing_push_poses.bvh
98    mazen_c3d_walkbackwards_stand_poses.bvh
65              mazen_c3d_kick_walk_poses.bvh
Name: file_name, dtype: object

40    mazen_c3d_dance_turntwist180_poses.bvh
67      mazen_c3d_punchboxing_kick_poses.bvh
35        mazen_c3d_dance_longjump_poses.bvh
Name: file_name, dtype: object

In [99]:
print("Success: {} out of {}".format(np.sum(Transitions['success'] == True), len(Transitions)))
print("Success %: {}".format(np.sum(Transitions['success'] == True)/len(Transitions) * 100))


Success: 0 out of 110
Success %: 0.0


### Investigation Summary

Maximum mean position error: nothing not mentioned
<br>


Maximum mean rotation error: nothing not mentioned
<br>

Worst performing Joint for position: Root <br>
Best performing Joint position: hip and back <br>


Worst performing Joint for rotation:  Root <br>
Best performing Joint rotation: torso and back <br>

similar issue with elbow, wrist, toe and ankles.

Other comments: As expected humanoids no longer float and is dealt with. Bound of 0.08 and 3 degrees is too tight (0).

# Compare Datasets

In [100]:
def compare_datasets(dfs):
  summary_dfs = []
  # summary statistics
  for name, df in dfs.items():
    obj = {'Name': name}
    obj['Mean_Percent_Time_taken_To_Imitate'] = np.mean(df['time_taken'] / df['clip_time_origin'])
    obj['Mean_Imit_Start_Frame'] = np.mean(df['frame_imit_starts'])
    obj['MPJPE'] = df[JOINT_MPE_NAMES].sum(axis=1).sum() / len(JOINT_NAMES) / len(df)
    obj['MPJRE'] = df[JOINT_MRE_NAMES].sum(axis=1).sum() / len(JOINT_NAMES) / len(df)

    for j in JOINT_MPE_NAMES:
      obj[j] = np.mean(df[j])

    for j in JOINT_MRE_NAMES:
      obj[j] = np.mean(df[j]
                       )
    summary_dfs.append(obj)

  summary_df = pd.DataFrame(summary_dfs)
  return summary_df

In [102]:
summary_df = compare_datasets(ALL_DFS)

In [103]:
summary_df.loc[:, ~summary_df.columns.isin([*JOINT_MPE_NAMES, *JOINT_MRE_NAMES])]

Name  Mean_Percent_Time_taken_To_Imitate  Mean_Imit_Start_Frame  \
0      BML_movi                            0.686082              33.363132   
1       BML_rub                            0.811205              56.146453   
2           CMU                            0.619710              76.396145   
3       DanceDB                            0.346019              55.660131   
4          EKUT                            0.663920              68.910920   
5          Eyes                            0.355434              74.918667   
6     MPI_HDM05                            0.384683              90.632558   
7    MPI_Limits                            0.353791              11.085714   
8      MPI_mosh                            0.477389              21.077922   
9           SFU                            0.442384              59.000000   
10  Transitions                            0.489713              94.172727   
11        Accad                            0.933145              58.757937   

       MPJPE     MPJRE  
0   0.041822  0.384683  
1   0.126307  0.362925  
2   0.089779  0.414358  
3   0.130365  0.582772  
4   0.139711  0.331456  
5   0.072421  0.424877  
6   0.087431  0.489307  
7   0.121918  0.548342  
8   0.085157  0.462389  
9   0.135007  0.493692  
10  0.061564  0.350689  
11  0.073408  0.490834

In [105]:
summary_df.loc[:, summary_df.columns.isin([*JOINT_MPE_NAMES, 'Name'])]

Name  RootJoint_MPE      lHip_MPE  lKnee_MPE  lAnkle_MPE  \
0      BML_movi       0.147505  3.017550e-08   0.040058    0.067738   
1       BML_rub       1.641779  6.537284e-08   0.053856    0.084678   
2           CMU       0.569543  4.610130e-08   0.070050    0.108506   
3       DanceDB       1.490491  5.535526e-08   0.064849    0.108572   
4          EKUT       0.585365  5.155331e-08   0.172435    0.271220   
5          Eyes       0.523817  3.878263e-08   0.052551    0.074933   
6     MPI_HDM05       0.835797  4.977815e-08   0.057004    0.085803   
7    MPI_Limits       0.956491  4.167115e-08   0.073052    0.135816   
8      MPI_mosh       0.198842  2.899001e-08   0.089340    0.136732   
9           SFU       1.316908  6.796888e-08   0.079742    0.132508   
10  Transitions       0.394901  3.832035e-08   0.050904    0.080498   
11        Accad       0.510837  6.154284e-08   0.061732    0.088647   

    lToeJoint_MPE      rHip_MPE  rKnee_MPE  rAnkle_MPE  rToeJoint_MPE  ...  \
0        0.073100  3.015394e-08   0.036539    0.058737       0.064381  ...   
1        0.095394  6.550586e-08   0.051173    0.083414       0.091852  ...   
2        0.120989  4.621502e-08   0.069834    0.106217       0.117329  ...   
3        0.122243  5.545998e-08   0.063421    0.101852       0.116386  ...   
4        0.288233  5.164364e-08   0.173380    0.273351       0.290776  ...   
5        0.083281  3.906150e-08   0.050888    0.072616       0.080558  ...   
6        0.096866  5.029243e-08   0.054903    0.080621       0.089236  ...   
7        0.146298  4.268258e-08   0.084020    0.134818       0.155659  ...   
8        0.147013  2.913222e-08   0.084615    0.129448       0.140109  ...   
9        0.141772  6.789113e-08   0.084543    0.130588       0.141043  ...   
10       0.088845  3.847199e-08   0.048666    0.077197       0.084858  ...   
11       0.100690  6.158920e-08   0.061214    0.086985       0.099819  ...   

    lowerback_torso_MPE  torso_head_MPE  lTorso_Clavicle_MPE  lShoulder_MPE  \
0              0.011854        0.024400             0.017460       0.021148   
1              0.013211        0.030382             0.021688       0.026095   
2              0.016896        0.044744             0.031212       0.038446   
3              0.016598        0.038193             0.026678       0.033148   
4              0.020371        0.052160             0.036542       0.044492   
5              0.015082        0.035054             0.024856       0.031611   
6              0.013283        0.036063             0.024736       0.027668   
7              0.016623        0.066124             0.042766       0.052068   
8              0.014001        0.051985             0.034241       0.046302   
9              0.022228        0.059685             0.041533       0.045513   
10             0.014399        0.034313             0.024543       0.023281   
11             0.014181        0.036617             0.025509       0.030450   

    lElbow_MPE  lWrist_MPE  rTorso_Clavicle_MPE  rShoulder_MPE  rElbow_MPE  \
0     0.049329    0.069291             0.017452       0.021640    0.047697   
1     0.061476    0.083453             0.021657       0.026836    0.060952   
2     0.091314    0.126551             0.031201       0.038307    0.091342   
3     0.078050    0.103705             0.026673       0.034218    0.079138   
4     0.102674    0.159537             0.036544       0.045099    0.100073   
5     0.080803    0.102697             0.024849       0.030175    0.073772   
6     0.066807    0.078877             0.024732       0.029892    0.066102   
7     0.095613    0.131948             0.042779       0.052395    0.103372   
8     0.109385    0.167063             0.034246       0.046346    0.108871   
9     0.089544    0.123996             0.041515       0.046741    0.084214   
10    0.055936    0.079015             0.024501       0.024686    0.056375   
11    0.069916    0.081483             0.025486       0.029806    0.065785   

    rWrist_MPE  
0     0.0681

In [106]:
summary_df.loc[:, summary_df.columns.isin([*JOINT_MRE_NAMES, 'Name'])]

Name  RootJoint_MRE  lHip_MRE  lKnee_MRE  lAnkle_MRE  \
0      BML_movi       2.029320  0.137398   0.198276    0.189049   
1       BML_rub       2.071962  0.184649   0.302736    0.232312   
2           CMU       1.956641  0.236842   0.317215    0.255159   
3       DanceDB       3.696831  0.219456   0.353628    0.398368   
4          EKUT       1.404615  0.444792   0.611929    0.371086   
5          Eyes       2.400145  0.197085   0.231579    0.223357   
6     MPI_HDM05       3.743015  0.211925   0.294205    0.224484   
7    MPI_Limits       2.635859  0.251941   0.418233    0.366591   
8      MPI_mosh       1.784896  0.266265   0.309176    0.233186   
9           SFU       3.166351  0.267787   0.422701    0.362655   
10  Transitions       1.804975  0.203475   0.283225    0.231711   
11        Accad       2.191303  0.281853   0.350771    0.247390   

    lToeJoint_MRE  rHip_MRE  rKnee_MRE  rAnkle_MRE  rToeJoint_MRE  ...  \
0        0.179522  0.128133   0.188120    0.189502       0.201007  ...   
1        0.145782  0.173716   0.264463    0.216476       0.128702  ...   
2        0.113204  0.229734   0.299672    0.247740       0.114076  ...   
3        0.302066  0.202628   0.351811    0.394309       0.412368  ...   
4        0.154211  0.449905   0.620712    0.403683       0.143119  ...   
5        0.059548  0.189378   0.230227    0.226294       0.056568  ...   
6        0.090057  0.211009   0.274083    0.221087       0.096872  ...   
7        0.068018  0.316077   0.357307    0.406157       0.065194  ...   
8        0.116830  0.249613   0.277952    0.221131       0.077612  ...   
9        0.186164  0.276040   0.391712    0.298816       0.160457  ...   
10       0.145303  0.193949   0.276038    0.245580       0.125703  ...   
11       0.133569  0.270265   0.338116    0.265227       0.139877  ...   

    lowerback_torso_MRE  torso_head_MRE  lTorso_Clavicle_MRE  lShoulder_MRE  \
0              0.100300        0.176317             0.146462       0.272128   
1              0.114197        0.160757             0.131174       0.232713   
2              0.151152        0.244787             0.186690       0.309740   
3              0.150583        0.352948             0.235793       0.382075   
4              0.127874        0.149043             0.151552       0.227542   
5              0.154496        0.242694             0.232601       0.347111   
6              0.140218        0.266792             0.212408       0.320585   
7              0.175706        0.307344             0.296166       0.383473   
8              0.133280        0.171259             0.205910       0.447718   
9              0.178208        0.252448             0.212822       0.372742   
10             0.177832        0.206188             0.147620       0.273934   
11             0.178121        0.223499             0.180631       0.277687   

    lElbow_MRE  lWrist_MRE  rTorso_Clavicle_MRE  rShoulder_MRE  rElbow_MRE  \
0     1.043904    0.285594             0.139344       0.279515    1.400658   
1     0.996732    0.260705             0.124788       0.223183    0.880165   
2     1.167737    0.295540             0.185107       0.312714    1.182155   
3     1.145448    0.552943             0.213265       0.388377    1.197666   
4     0.241611    0.181626             0.148286       0.225121    0.243170   
5     1.027323    0.400893             0.195726       0.338302    1.189100   
6     1.075661    0.414770             0.200768       0.291545    0.952670   
7     1.472110    0.513578             0.296330       0.401566    1.420545   
8     1.672166    0.355196             0.193094       0.399690    1.638155   
9     0.911905    0.395148             0.210905       0.342164    0.878913   
10    0.886644    0.295190             0.149300       0.258555    0.633920   
11    2.019190    0.287629             0.168589       0.258151    1.543271   

    rWrist_MRE  
0     0.305674  
1     0.273302  
2     0.305197  
3     0.550654  
4     0.167523  
5     0.394939  
6     0.390477